/**
 * BreadthStockModal.js
 *
 * Drill-down stock list modal for the Stockbee Market Monitor.
 * Reads from /breadth_stocks_{filter}.json (pre-generated by breadth_stocks_builder.py).
 *
 * Two views:
 *   List    — flat table: #, Ticker, Company, $Vol, ADR%, Change%
 *   Group   — grouped by industry with copy-ticker buttons
 */

import { memo, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Check, Copy, ExternalLink, Layers, LayoutList, Loader2, X } from "lucide-react";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function fmtPct(v) {
  if (v == null) return "—";
  const s = Math.abs(v).toFixed(2);
  return v > 0 ? `+${s}%` : `-${s}%`;
}

function fmtPrice(v) {
  if (v == null) return "—";
  return `$${v.toFixed(2)}`;
}

function changeCls(v) {
  if (v == null) return "text-zinc-500";
  return v > 0 ? "text-emerald-400" : "text-rose-400";
}

// ---------------------------------------------------------------------------
// Copy button
// ---------------------------------------------------------------------------

const CopyButton = memo(function CopyButton({ tickers, label }) {
  const [copied, setCopied] = useState(false);
  const timer = useRef(null);

  const handleCopy = useCallback((e) => {
    e.stopPropagation();
    navigator.clipboard.writeText(tickers.join(",")).then(() => {
      setCopied(true);
      clearTimeout(timer.current);
      timer.current = setTimeout(() => setCopied(false), 1800);
    });
  }, [tickers]);

  useEffect(() => () => clearTimeout(timer.current), []);

  return (
    <button
      onClick={handleCopy}
      title={`Copy ${tickers.length} tickers`}
      className={`inline-flex items-center gap-1 rounded px-2 py-0.5 text-xs transition-colors
        hover:bg-zinc-700 ${copied ? "text-emerald-400" : "text-zinc-500 hover:text-zinc-300"}`}
    >
      {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
      <span>{copied ? "Copied" : (label ?? tickers.length)}</span>
    </button>
  );
});

// ---------------------------------------------------------------------------
// Per-filter column label for the Change% column
// ---------------------------------------------------------------------------

const CHANGE_COL_LABEL = {
  up4:     "1D Change%",
  dn4:     "1D Change%",
  up25q:   "Quarterly Change%",
  dn25q:   "Quarterly Change%",
  up25m:   "25% Monthly Change%",
  dn25m:   "25% Monthly Change%",
  up50m:   "50% Monthly Change%",
  dn50m:   "50% Monthly Change%",
  up13_34: "1.5M Change%",
  dn13_34: "1.5M Change%",
};

// Which field to read for the last (perf) column, keyed by scanner filter id.
// For 34D scanners: perf_34d is not yet in the schema; perf_1m is used as the
// closest approximation until breadth_stocks_builder.py provides perf_34d.
const PERF_FIELD = {
  up4:     "change_pct",
  dn4:     "change_pct",
  up25q:   "perf_3m",
  dn25q:   "perf_3m",
  up25m:   "perf_1m",
  dn25m:   "perf_1m",
  up50m:   "perf_1m",
  dn50m:   "perf_1m",
  up13_34: "perf_34d", // TODO: replace with dedicated field once schema has it
  dn13_34: "perf_34d",
};

// Client-side threshold guard for the last column.
// Only applied to up4/dn4 because change_pct comes directly from Finviz and
// is reliable. For quarterly/monthly/34D scanners, Finviz already pre-filters
// to the stated threshold using its own period calculation; our yfinance-based
// perf_1m/perf_3m/perf_34d uses a different lookback window and does not match
// closely enough to use as a hard filter without excluding valid stocks.
const PERF_THRESHOLD = {
  up4:  4,
  dn4: -4,
};

// Read a stock's perf value for the given field, with fallback for perf_34d.
function getPerfValue(s, field) {
  if (field === "perf_34d") {
    // perf_34d not yet available — fall back to perf_1m as approximation
    return s.perf_34d ?? s.perf_1m ?? null;
  }
  return s[field] ?? null;
}

// Parse dollar_volume which may arrive as a formatted string ("$1.2B") or number
function parseDollarVolume(v) {
  if (v == null) return null;
  if (typeof v === "number") return v;
  const s = String(v).replace(/[$,\s]/g, "");
  const m = s.match(/^([\d.]+)([KMBT]?)$/i);
  if (!m) return null;
  const mult = { K: 1e3, M: 1e6, B: 1e9, T: 1e12 }[m[2].toUpperCase()] ?? 1;
  return parseFloat(m[1]) * mult;
}

// ---------------------------------------------------------------------------
// Stock detail modal — Chart / Fundamentals / News
// ---------------------------------------------------------------------------

// TradingView Financials widget — injected via script tag (iframe blocks financials pages)
const TradingViewFinancials = memo(function TradingViewFinancials({ ticker }) {
  const containerRef = useRef(null);

  useEffect(() => {
    if (!containerRef.current) return;
    containerRef.current.innerHTML = "";
    const widget = document.createElement("div");
    widget.className = "tradingview-widget-container__widget";
    widget.style.cssText = "height:100%;width:100%";
    containerRef.current.appendChild(widget);

    const script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "https://s3.tradingview.com/external-embedding/embed-widget-financials.js";
    script.async = true;
    script.textContent = JSON.stringify({
      symbol: ticker,
      width: "100%",
      height: 830,
      locale: "en",
      colorTheme: "dark",
      isTransparent: false,
      displayMode: "regular",
    });
    containerRef.current.appendChild(script);

    return () => { if (containerRef.current) containerRef.current.innerHTML = ""; };
  }, [ticker]);

  return <div ref={containerRef} className="tradingview-widget-container h-full w-full" />;
});

const StockDetailModal = memo(function StockDetailModal({ stock, filter, onClose }) {
  const [tab, setTab] = useState("chart");
  const [news, setNews] = useState([]);
  const [newsLoading, setNewsLoading] = useState(true);
  const [newsError, setNewsError] = useState(null);

  const perfField      = PERF_FIELD[filter] ?? "change_pct";
  const changeColLabel = CHANGE_COL_LABEL[filter] ?? "Change%";
  const { ticker, company } = stock;
  const perfVal = getPerfValue(stock, perfField);

  // Fetch news EAGERLY on mount so it's ready when the user clicks the News tab.
  // Uses corsproxy.io which is significantly faster than allorigins.win.
  useEffect(() => {
    setNewsLoading(true);
    setNewsError(null);
    setNews([]);
    const rss   = `https://feeds.finance.yahoo.com/rss/2.0/headline?s=${ticker}&region=US&lang=en-US`;
    const proxy = `https://corsproxy.io/?url=${encodeURIComponent(rss)}`;
    const ctrl  = new AbortController();
    fetch(proxy, { signal: ctrl.signal })
      .then((r) => r.text())
      .then((xml) => {
        const doc   = new DOMParser().parseFromString(xml, "text/xml");
        const items = Array.from(doc.querySelectorAll("item")).slice(0, 12).map((el) => ({
          title: el.querySelector("title")?.textContent ?? "",
          link:  el.querySelector("link")?.textContent ?? "",
          date:  el.querySelector("pubDate")?.textContent ?? "",
        }));
        setNews(items);
        setNewsLoading(false);
      })
      .catch((e) => {
        if (e.name === "AbortError") return;
        setNewsError("Failed to load news.");
        setNewsLoading(false);
      });
    return () => ctrl.abort();
  }, [ticker]);

  // Escape closes only this panel (capture phase stops propagation to parent)
  useEffect(() => {
    const handler = (e) => { if (e.key === "Escape") { e.stopPropagation(); onClose(); } };
    window.addEventListener("keydown", handler, true);
    return () => window.removeEventListener("keydown", handler, true);
  }, [onClose]);

  // Compact scanner metrics shown above the TradingView fundamentals widget
  const scannerMetrics = [
    { label: "Price",        value: stock.price != null ? `$${stock.price.toFixed(2)}` : "—", cls: "text-zinc-200" },
    { label: "1D Chg",       value: fmtPct(stock.change_pct),  cls: changeCls(stock.change_pct)  },
    { label: "ADR%",         value: stock.adr_pct != null ? `${stock.adr_pct.toFixed(1)}%` : "—", cls: "text-zinc-200" },
    { label: "$ Vol",        value: stock.dollar_volume || "—", cls: "text-zinc-200" },
    { label: "Mkt Cap",      value: stock.market_cap_b != null ? `$${stock.market_cap_b.toFixed(1)}B` : "—", cls: "text-zinc-200" },
    { label: changeColLabel, value: fmtPct(perfVal),            cls: changeCls(perfVal)            },
    { label: "1M",           value: fmtPct(stock.perf_1m),     cls: changeCls(stock.perf_1m)      },
    { label: "3M",           value: fmtPct(stock.perf_3m),     cls: changeCls(stock.perf_3m)      },
  ];

  return (
    <div
      className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 backdrop-blur-sm"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div className="relative flex h-[92vh] w-full max-w-4xl flex-col rounded-xl border border-zinc-600 bg-zinc-950 shadow-2xl">

        {/* Header */}
        <div className="flex items-center gap-2 border-b border-zinc-800 px-4 py-2.5">
          <span className="font-mono text-base font-bold text-white">{ticker}</span>
          <span className="flex-1 truncate text-xs text-zinc-400">{company}</span>
          <a href={`https://finviz.com/quote.ashx?t=${ticker}`} target="_blank" rel="noopener noreferrer"
             title="Open in Finviz" className="text-zinc-500 hover:text-cyan-400 transition-colors">
            <ExternalLink className="h-3.5 w-3.5" />
          </a>
          <button onClick={onClose} className="rounded p-1 text-zinc-500 hover:bg-zinc-700 hover:text-zinc-200" aria-label="Close">
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Tab bar */}
        <div className="flex gap-1 border-b border-zinc-800 px-4">
          {["chart", "fundamentals", "news"].map((t) => (
            <button key={t} onClick={() => setTab(t)}
              className={`capitalize px-3 py-1.5 text-xs border-b-2 -mb-px transition-colors
                ${tab === t ? "border-cyan-400 text-cyan-400" : "border-transparent text-zinc-500 hover:text-zinc-300"}`}>
              {t}
            </button>
          ))}
        </div>

        {/* Tab body */}
        <div className="min-h-0 flex-1 flex flex-col">

          {tab === "chart" && (
            <iframe key={ticker} title={`${ticker} chart`}
              src={`https://www.tradingview.com/widgetembed/?symbol=${ticker}&interval=D&theme=dark&style=1&withdateranges=1&hide_legend=0&saveimage=1&hide_side_toolbar=0&allow_symbol_change=1`}
              className="w-full flex-1 border-0 rounded-b-xl" allowFullScreen />
          )}

          {tab === "fundamentals" && (
            <div className="flex flex-col flex-1 min-h-0">
              {/* Compact scanner metrics strip */}
              <div className="flex flex-wrap gap-x-4 gap-y-1 border-b border-zinc-800 px-4 py-2">
                {scannerMetrics.map(({ label, value, cls }) => (
                  <div key={label} className="flex items-baseline gap-1.5">
                    <span className="text-[10px] text-zinc-500 uppercase tracking-wide">{label}</span>
                    <span className={`font-mono text-xs font-semibold ${cls}`}>{value}</span>
                  </div>
                ))}
              </div>
              {/* TradingView Financials widget — fixed height, scrollable */}
              <div className="flex-1 overflow-y-auto">
                <TradingViewFinancials ticker={ticker} />
              </div>
            </div>
          )}

          {tab === "news" && (
            <div className="flex-1 overflow-y-auto p-3">
              {newsLoading ? (
                <div className="flex justify-center py-10">
                  <Loader2 className="h-5 w-5 animate-spin text-zinc-500" />
                </div>
              ) : newsError ? (
                <div className="py-10 text-center">
                  <p className="text-sm text-rose-400">{newsError}</p>
                  <a href={`https://finance.yahoo.com/quote/${ticker}/news`} target="_blank" rel="noopener noreferrer"
                     className="mt-2 block text-xs text-zinc-400 hover:text-cyan-400">
                    View on Yahoo Finance →
                  </a>
                </div>
              ) : news.length === 0 ? (
                <p className="py-10 text-center text-sm text-zinc-500">No recent news found.</p>
              ) : (
                <div className="space-y-1.5">
                  {news.map((item, i) => (
                    <a key={i} href={item.link} target="_blank" rel="noopener noreferrer"
                       className="block rounded-lg bg-zinc-800/50 px-3 py-2 hover:bg-zinc-700/60 transition-colors">
                      <div className="text-xs leading-snug text-zinc-200">{item.title}</div>
                      {item.date && (
                        <div className="mt-0.5 text-[10px] text-zinc-500">
                          {new Date(item.date).toLocaleString("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}
                        </div>
                      )}
                    </a>
                  ))}
                </div>
              )}
            </div>
          )}

        </div>
      </div>
    </div>
  );
});

// ---------------------------------------------------------------------------
// List view — matches screenshot exactly: #, Ticker, Company, $Vol, ADR%, Change%
// ---------------------------------------------------------------------------

// Static column definitions for the first four sortable columns.
// The fifth (perf) column is built dynamically inside ListView using the filter prop.
const BASE_SORT_COLS = [
  { key: "ticker",        label: "Ticker",  align: "left",  numeric: false },
  { key: "company",       label: "Company", align: "left",  numeric: false },
  { key: "dollar_volume", label: "$ Vol",   align: "right", numeric: true  },
  { key: "adr_pct",       label: "ADR%",    align: "right", numeric: true  },
];

const ListView = memo(function ListView({ stocks, filter, onStockClick }) {
  const [sortKey, setSortKey] = useState(null);
  const [sortDir, setSortDir] = useState("asc");

  const changeColLabel = CHANGE_COL_LABEL[filter] ?? "Change%";
  const perfField = PERF_FIELD[filter] ?? "change_pct";

  // Build full column list with dynamic perf column appended
  const sortCols = [
    ...BASE_SORT_COLS,
    { key: perfField, label: null, align: "right", numeric: true },
  ];

  // Fixed handleSort — reads sortKey/sortDir directly from closure, no functional updater side-effects
  const handleSort = (key) => {
    if (sortKey === key) {
      setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      setSortKey(key);
      setSortDir("asc");
    }
  };

  const sortedStocks = useMemo(() => {
    if (!sortKey) return stocks;
    return [...stocks].sort((a, b) => {
      let av, bv;
      if (sortKey === "dollar_volume") {
        av = parseDollarVolume(a.dollar_volume);
        bv = parseDollarVolume(b.dollar_volume);
      } else if (sortKey === perfField) {
        av = getPerfValue(a, perfField);
        bv = getPerfValue(b, perfField);
      } else {
        av = a[sortKey];
        bv = b[sortKey];
      }
      // Nulls always last
      if (av == null && bv == null) return 0;
      if (av == null) return 1;
      if (bv == null) return -1;
      const cmp = typeof av === "string" ? av.localeCompare(bv) : av - bv;
      return sortDir === "asc" ? cmp : -cmp;
    });
  }, [stocks, sortKey, sortDir, perfField]);

  if (!stocks.length) {
    return <p className="py-12 text-center text-sm text-zinc-500">No stocks match the current filters.</p>;
  }

  const SortIcon = ({ colKey }) => {
    if (sortKey !== colKey) return <span className="ml-0.5 text-zinc-600">⇅</span>;
    return <span className="ml-0.5 text-white">{sortDir === "asc" ? "↑" : "↓"}</span>;
  };

  return (
    <div className="overflow-x-auto">
      <table className="w-full border-collapse text-left text-xs">
        <thead>
          <tr className="border-b border-zinc-800 text-zinc-500">
            <th className="w-8 py-2 pr-2 text-right font-medium">#</th>
            {sortCols.map((col) => {
              const label = col.key === perfField && col.label === null ? changeColLabel : col.label;
              return (
                <th
                  key={col.key}
                  onClick={() => handleSort(col.key)}
                  className={`px-2 py-2 font-medium cursor-pointer select-none hover:text-zinc-300 transition-colors
                    ${col.align === "right" ? "text-right" : ""}`}
                >
                  {label}<SortIcon colKey={col.key} />
                </th>
              );
            })}
          </tr>
        </thead>
        <tbody>
          {sortedStocks.map((s, i) => (
            <tr
              key={s.ticker}
              className="border-b border-zinc-800/50 hover:bg-zinc-800/30"
            >
              <td className="py-1.5 pr-2 text-right font-mono text-zinc-600">{i + 1}</td>
              <td className="px-2 py-1.5 font-mono font-semibold text-cyan-400">
                <button
                  onClick={() => onStockClick(s)}
                  className="hover:underline hover:text-white transition-colors"
                >
                  {s.ticker}
                </button>
              </td>
              <td className="max-w-[220px] truncate px-2 py-1.5 text-zinc-300">
                {s.company || "—"}
              </td>
              <td className="px-2 py-1.5 text-right font-mono text-zinc-400">
                {s.dollar_volume || "—"}
              </td>
              <td className="px-2 py-1.5 text-right font-mono text-zinc-300">
                {s.adr_pct != null ? `${s.adr_pct.toFixed(1)}%` : "—"}
              </td>
              <td className={`px-2 py-1.5 text-right font-mono font-semibold ${changeCls(getPerfValue(s, perfField))}`}>
                {fmtPct(getPerfValue(s, perfField))}
              </td>
            </tr>
          ))}
        </tbody>
        {/* Totals footer */}
        <tfoot>
          <tr className="border-t border-zinc-700 text-zinc-600 text-xs">
            <td colSpan={3} className="py-1.5 pr-2 text-right font-mono">
              {stocks.length} stocks
            </td>
            <td colSpan={3} />
          </tr>
        </tfoot>
      </table>
    </div>
  );
});

// ---------------------------------------------------------------------------
// Group view
// ---------------------------------------------------------------------------

function groupByIndustry(stocks) {
  const map = new Map();
  for (const s of stocks) {
    const key = s.industry || "Other";
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(s);
  }
  return [...map.entries()]
    .map(([industry, items]) => ({ industry, items }))
    .sort((a, b) => b.items.length - a.items.length);
}

// GroupRow receives pre-sorted items and the active perf field from GroupView.
const GroupRow = memo(function GroupRow({ industry, items, perfField, onStockClick }) {
  const [open, setOpen] = useState(false);
  const tickers = items.map((s) => s.ticker);

  return (
    <div className="border-t border-zinc-800 first:border-t-0">
      {/* Industry header row */}
      <div
        className="group flex cursor-pointer items-center gap-2 px-3 py-2 hover:bg-zinc-800/40"
        onClick={() => setOpen((o) => !o)}
      >
        <span className="text-zinc-500 text-xs">{open ? "▾" : "▸"}</span>
        <span className="flex-1 text-sm font-medium text-zinc-200">{industry}</span>
        <span className="text-xs text-zinc-500">{items.length}</span>
        <span className="opacity-0 transition-opacity group-hover:opacity-100">
          <CopyButton tickers={tickers} />
        </span>
      </div>

      {open && (
        <div className="ml-4 max-h-64 overflow-y-auto border-l border-zinc-700 pb-1">
          {items.map((s) => {
            const perfVal = getPerfValue(s, perfField);
            return (
              <div
                key={s.ticker}
                className="flex items-center gap-3 px-3 py-1 text-xs hover:bg-zinc-800/30"
              >
                <button
                  onClick={() => onStockClick(s)}
                  className="w-14 font-mono font-semibold text-cyan-400 hover:underline hover:text-white transition-colors text-left"
                >
                  {s.ticker}
                </button>
                <span className="flex-1 truncate text-zinc-400">{s.company}</span>
                <span className="w-12 text-right font-mono text-zinc-500">
                  {s.adr_pct != null ? `${s.adr_pct.toFixed(1)}%` : "—"}
                </span>
                <span className={`w-16 text-right font-mono font-semibold ${changeCls(perfVal)}`}>
                  {fmtPct(perfVal)}
                </span>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
});

const GroupView = memo(function GroupView({ stocks, filter, onStockClick }) {
  const [sortKey, setSortKey] = useState(null);
  const [sortDir, setSortDir] = useState("asc");

  const perfField     = PERF_FIELD[filter] ?? "change_pct";
  const changeColLabel = CHANGE_COL_LABEL[filter] ?? "Change%";

  // Fixed handleSort — reads state from closure, no functional-updater side-effects
  const handleSort = (key) => {
    if (sortKey === key) {
      setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      setSortKey(key);
      setSortDir("asc");
    }
  };

  const SortIcon = ({ colKey }) => {
    if (sortKey !== colKey) return <span className="ml-0.5 text-zinc-600">⇅</span>;
    return <span className="ml-0.5 text-white">{sortDir === "asc" ? "↑" : "↓"}</span>;
  };

  // Build groups then sort each group's items by the active column
  const groups = useMemo(() => {
    const raw = groupByIndustry(stocks);
    if (!sortKey) return raw;
    return raw.map((g) => ({
      ...g,
      items: [...g.items].sort((a, b) => {
        let av, bv;
        if (sortKey === perfField) {
          av = getPerfValue(a, perfField);
          bv = getPerfValue(b, perfField);
        } else if (sortKey === "adr_pct") {
          av = a.adr_pct;
          bv = b.adr_pct;
        } else {
          av = a[sortKey];
          bv = b[sortKey];
        }
        if (av == null && bv == null) return 0;
        if (av == null) return 1;
        if (bv == null) return -1;
        const cmp = typeof av === "string" ? av.localeCompare(bv) : av - bv;
        return sortDir === "asc" ? cmp : -cmp;
      }),
    }));
  }, [stocks, sortKey, sortDir, perfField]);

  if (!groups.length) {
    return <p className="py-12 text-center text-sm text-zinc-500">No groups to display.</p>;
  }

  // Column config for the stock-row header (mirrors the expanded row layout)
  const GROUP_STOCK_COLS = [
    { key: "ticker",   label: "Ticker",       align: "left",  cls: "w-14" },
    { key: "company",  label: "Company",       align: "left",  cls: "flex-1" },
    { key: "adr_pct",  label: "ADR%",          align: "right", cls: "w-12" },
    { key: perfField,  label: changeColLabel,  align: "right", cls: "w-16" },
  ];

  return (
    <div>
      {/* Industry / Count header */}
      <div className="flex items-center gap-2 border-b border-zinc-800 px-3 py-1.5 text-xs font-medium text-zinc-600">
        <span className="flex-1">Industry</span>
        <span>Count</span>
      </div>

      {/* Stock-column sort header (always visible) */}
      <div className="flex items-center gap-3 border-b border-zinc-800 bg-zinc-900/80 px-3 py-1 pl-[3.25rem] text-xs font-medium text-zinc-500 sticky top-0 z-10">
        {GROUP_STOCK_COLS.map((col) => (
          <button
            key={col.key}
            onClick={() => handleSort(col.key)}
            className={`${col.cls} cursor-pointer select-none hover:text-zinc-300 transition-colors
              ${col.align === "right" ? "text-right" : "text-left"}`}
          >
            {col.label}<SortIcon colKey={col.key} />
          </button>
        ))}
      </div>

      {groups.map((g) => (
        <GroupRow key={g.industry} industry={g.industry} items={g.items} perfField={perfField} onStockClick={onStockClick} />
      ))}
    </div>
  );
});

// ---------------------------------------------------------------------------
// Main modal
// ---------------------------------------------------------------------------

const BreadthStockModal = memo(function BreadthStockModal({ filter, filterLabel, onClose }) {
  const [view, setView] = useState("list");
  const [stocks, setStocks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedStock, setSelectedStock] = useState(null);
  const abortRef = useRef(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    abortRef.current?.abort();
    const ctrl = new AbortController();
    abortRef.current = ctrl;

    try {
      const res = await fetch(
        `${process.env.PUBLIC_URL}/breadth_stocks_${filter}.json?_=${Date.now()}`,
        { signal: ctrl.signal }
      );
      if (!res.ok) throw new Error(`HTTP ${res.status} — stock list not found. Run breadth_stocks_builder.py first.`);
      const data = await res.json();
      setStocks(data.stocks ?? []);
    } catch (e) {
      if (e.name === "AbortError") return;
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, [filter]);

  useEffect(() => {
    void load();
    return () => abortRef.current?.abort();
  }, [load]);

  // Close on Escape
  useEffect(() => {
    const handler = (e) => { if (e.key === "Escape") onClose(); };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onClose]);

  // Client-side threshold guard: enforce each scanner's minimum perf cutoff
  // so edge-case entries from Finviz never slip through to the table.
  const displayStocks = useMemo(() => {
    const threshold = PERF_THRESHOLD[filter];
    if (threshold == null) return stocks;
    const field = PERF_FIELD[filter] ?? "change_pct";
    if (threshold > 0) {
      return stocks.filter((s) => (getPerfValue(s, field) ?? -Infinity) >= threshold);
    } else {
      return stocks.filter((s) => (getPerfValue(s, field) ?? Infinity) <= threshold);
    }
  }, [stocks, filter]);

  const allTickers = displayStocks.map((s) => s.ticker);

  return (
    <>
    {/* Backdrop */}
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      {/* Panel */}
      <div className="relative flex h-[85vh] w-full max-w-3xl flex-col rounded-xl border border-zinc-700 bg-zinc-900 shadow-2xl">

        {/* Header */}
        <div className="flex items-center gap-3 border-b border-zinc-800 px-4 py-3">
          <div className="flex-1">
            <h2 className="text-sm font-semibold text-zinc-100">{filterLabel}</h2>
            {!loading && (
              <p className="text-xs text-zinc-500">
                {stocks.length} stocks · min $1B mkt cap
              </p>
            )}
          </div>

          {/* List / Group toggle */}
          <div className="flex items-center gap-1 rounded-lg border border-zinc-700 p-0.5">
            <button
              onClick={() => setView("list")}
              title="List view"
              className={`flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs transition-colors
                ${view === "list" ? "bg-zinc-700 text-zinc-100" : "text-zinc-400 hover:text-zinc-200"}`}
            >
              <LayoutList className="h-3.5 w-3.5" />
              List
            </button>
            <button
              onClick={() => setView("group")}
              title="Group by industry"
              className={`flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs transition-colors
                ${view === "group" ? "bg-zinc-700 text-zinc-100" : "text-zinc-400 hover:text-zinc-200"}`}
            >
              <Layers className="h-3.5 w-3.5" />
              Group
            </button>
          </div>

          {/* Copy all */}
          {allTickers.length > 0 && (
            <CopyButton tickers={allTickers} label="Copy" />
          )}

          {/* Close */}
          <button
            onClick={onClose}
            className="rounded p-1 text-zinc-500 hover:bg-zinc-700 hover:text-zinc-200"
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Body */}
        <div className="min-h-0 flex-1 overflow-y-auto">
          {loading ? (
            <div className="flex h-full items-center justify-center">
              <Loader2 className="h-6 w-6 animate-spin text-zinc-500" />
            </div>
          ) : error ? (
            <div className="flex h-full flex-col items-center justify-center gap-2 text-sm text-rose-400 px-6 text-center">
              <p>{error}</p>
              <button
                onClick={() => void load()}
                className="mt-2 text-xs text-zinc-400 underline hover:text-zinc-200"
              >
                Retry
              </button>
            </div>
          ) : view === "list" ? (
            <ListView stocks={displayStocks} filter={filter} onStockClick={setSelectedStock} />
          ) : (
            <GroupView stocks={displayStocks} filter={filter} onStockClick={setSelectedStock} />
          )}
        </div>
      </div>
    </div>

    {/* Stock detail overlay — Chart / Fundamentals / News */}
    {selectedStock && (
      <StockDetailModal
        stock={selectedStock}
        filter={filter}
        onClose={() => setSelectedStock(null)}
      />
    )}
    </>
  );
});

export default BreadthStockModal;
