/**
 * BreadthStockModal.js
 *
 * Drill-down stock list modal for the Stockbee Market Monitor.
 * Reads from /breadth_stocks_{filter}.json (pre-generated by breadth_stocks_builder.py).
 *
 * Two views:
 *   List    — flat table: #, Ticker, Company, $Vol, ADR%, Change%
 *   Group   — grouped by industry with copy-ticker buttons
 */

import { memo, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Check, Copy, Layers, LayoutList, Loader2, X } from "lucide-react";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function fmtPct(v) {
  if (v == null) return "—";
  const s = Math.abs(v).toFixed(2);
  return v > 0 ? `+${s}%` : `-${s}%`;
}

function fmtPrice(v) {
  if (v == null) return "—";
  return `$${v.toFixed(2)}`;
}

function changeCls(v) {
  if (v == null) return "text-zinc-500";
  return v > 0 ? "text-emerald-400" : "text-rose-400";
}

// ---------------------------------------------------------------------------
// Copy button
// ---------------------------------------------------------------------------

const CopyButton = memo(function CopyButton({ tickers, label }) {
  const [copied, setCopied] = useState(false);
  const timer = useRef(null);

  const handleCopy = useCallback((e) => {
    e.stopPropagation();
    navigator.clipboard.writeText(tickers.join(",")).then(() => {
      setCopied(true);
      clearTimeout(timer.current);
      timer.current = setTimeout(() => setCopied(false), 1800);
    });
  }, [tickers]);

  useEffect(() => () => clearTimeout(timer.current), []);

  return (
    <button
      onClick={handleCopy}
      title={`Copy ${tickers.length} tickers`}
      className={`inline-flex items-center gap-1 rounded px-2 py-0.5 text-xs transition-colors
        hover:bg-zinc-700 ${copied ? "text-emerald-400" : "text-zinc-500 hover:text-zinc-300"}`}
    >
      {copied ? <Check className="h-3 w-3" /> : <Copy className="h-3 w-3" />}
      <span>{copied ? "Copied" : (label ?? tickers.length)}</span>
    </button>
  );
});

// ---------------------------------------------------------------------------
// Per-filter column label for the Change% column
// ---------------------------------------------------------------------------

const CHANGE_COL_LABEL = {
  up4:     "1D Change%",
  dn4:     "1D Change%",
  up25q:   "Quarterly Change%",
  dn25q:   "Quarterly Change%",
  up25m:   "25% Monthly Change%",
  dn25m:   "25% Monthly Change%",
  up50m:   "50% Monthly Change%",
  dn50m:   "50% Monthly Change%",
  up13_34: "1.5M Change%",
  dn13_34: "1.5M Change%",
};

// Which field to read for the last (perf) column, keyed by scanner filter id.
// For 34D scanners: perf_34d is not yet in the schema; perf_1m is used as the
// closest approximation until breadth_stocks_builder.py provides perf_34d.
const PERF_FIELD = {
  up4:     "change_pct",
  dn4:     "change_pct",
  up25q:   "perf_3m",
  dn25q:   "perf_3m",
  up25m:   "perf_1m",
  dn25m:   "perf_1m",
  up50m:   "perf_1m",
  dn50m:   "perf_1m",
  up13_34: "perf_34d", // TODO: replace with dedicated field once schema has it
  dn13_34: "perf_34d",
};

// Read a stock's perf value for the given field, with fallback for perf_34d.
function getPerfValue(s, field) {
  if (field === "perf_34d") {
    // perf_34d not yet available — fall back to perf_1m as approximation
    return s.perf_34d ?? s.perf_1m ?? null;
  }
  return s[field] ?? null;
}

// Parse dollar_volume which may arrive as a formatted string ("$1.2B") or number
function parseDollarVolume(v) {
  if (v == null) return null;
  if (typeof v === "number") return v;
  const s = String(v).replace(/[$,\s]/g, "");
  const m = s.match(/^([\d.]+)([KMBT]?)$/i);
  if (!m) return null;
  const mult = { K: 1e3, M: 1e6, B: 1e9, T: 1e12 }[m[2].toUpperCase()] ?? 1;
  return parseFloat(m[1]) * mult;
}

// ---------------------------------------------------------------------------
// List view — matches screenshot exactly: #, Ticker, Company, $Vol, ADR%, Change%
// ---------------------------------------------------------------------------

// Static column definitions for the first four sortable columns.
// The fifth (perf) column is built dynamically inside ListView using the filter prop.
const BASE_SORT_COLS = [
  { key: "ticker",        label: "Ticker",  align: "left",  numeric: false },
  { key: "company",       label: "Company", align: "left",  numeric: false },
  { key: "dollar_volume", label: "$ Vol",   align: "right", numeric: true  },
  { key: "adr_pct",       label: "ADR%",    align: "right", numeric: true  },
];

const ListView = memo(function ListView({ stocks, filter }) {
  const [sortKey, setSortKey] = useState(null);
  const [sortDir, setSortDir] = useState("asc");

  const changeColLabel = CHANGE_COL_LABEL[filter] ?? "Change%";
  const perfField = PERF_FIELD[filter] ?? "change_pct";

  // Build full column list with dynamic perf column appended
  const sortCols = [
    ...BASE_SORT_COLS,
    { key: perfField, label: null, align: "right", numeric: true },
  ];

  // Fixed handleSort — reads sortKey/sortDir directly from closure, no functional updater side-effects
  const handleSort = (key) => {
    if (sortKey === key) {
      setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    } else {
      setSortKey(key);
      setSortDir("asc");
    }
  };

  const sortedStocks = useMemo(() => {
    if (!sortKey) return stocks;
    return [...stocks].sort((a, b) => {
      let av, bv;
      if (sortKey === "dollar_volume") {
        av = parseDollarVolume(a.dollar_volume);
        bv = parseDollarVolume(b.dollar_volume);
      } else if (sortKey === perfField) {
        av = getPerfValue(a, perfField);
        bv = getPerfValue(b, perfField);
      } else {
        av = a[sortKey];
        bv = b[sortKey];
      }
      // Nulls always last
      if (av == null && bv == null) return 0;
      if (av == null) return 1;
      if (bv == null) return -1;
      const cmp = typeof av === "string" ? av.localeCompare(bv) : av - bv;
      return sortDir === "asc" ? cmp : -cmp;
    });
  }, [stocks, sortKey, sortDir, perfField]);

  if (!stocks.length) {
    return <p className="py-12 text-center text-sm text-zinc-500">No stocks match the current filters.</p>;
  }

  const SortIcon = ({ colKey }) => {
    if (sortKey !== colKey) return <span className="ml-0.5 text-zinc-600">⇅</span>;
    return <span className="ml-0.5 text-white">{sortDir === "asc" ? "↑" : "↓"}</span>;
  };

  return (
    <div className="overflow-x-auto">
      <table className="w-full border-collapse text-left text-xs">
        <thead>
          <tr className="border-b border-zinc-800 text-zinc-500">
            <th className="w-8 py-2 pr-2 text-right font-medium">#</th>
            {sortCols.map((col) => {
              const label = col.key === perfField && col.label === null ? changeColLabel : col.label;
              return (
                <th
                  key={col.key}
                  onClick={() => handleSort(col.key)}
                  className={`px-2 py-2 font-medium cursor-pointer select-none hover:text-zinc-300 transition-colors
                    ${col.align === "right" ? "text-right" : ""}`}
                >
                  {label}<SortIcon colKey={col.key} />
                </th>
              );
            })}
          </tr>
        </thead>
        <tbody>
          {sortedStocks.map((s, i) => (
            <tr
              key={s.ticker}
              className="border-b border-zinc-800/50 hover:bg-zinc-800/30"
            >
              <td className="py-1.5 pr-2 text-right font-mono text-zinc-600">{i + 1}</td>
              <td className="px-2 py-1.5 font-mono font-semibold text-cyan-400">
                <a
                  href={`https://finviz.com/quote.ashx?t=${s.ticker}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:underline"
                >
                  {s.ticker}
                </a>
              </td>
              <td className="max-w-[220px] truncate px-2 py-1.5 text-zinc-300">
                {s.company || "—"}
              </td>
              <td className="px-2 py-1.5 text-right font-mono text-zinc-400">
                {s.dollar_volume || "—"}
              </td>
              <td className="px-2 py-1.5 text-right font-mono text-zinc-300">
                {s.adr_pct != null ? `${s.adr_pct.toFixed(1)}%` : "—"}
              </td>
              <td className={`px-2 py-1.5 text-right font-mono font-semibold ${changeCls(getPerfValue(s, perfField))}`}>
                {fmtPct(getPerfValue(s, perfField))}
              </td>
            </tr>
          ))}
        </tbody>
        {/* Totals footer */}
        <tfoot>
          <tr className="border-t border-zinc-700 text-zinc-600 text-xs">
            <td colSpan={3} className="py-1.5 pr-2 text-right font-mono">
              {stocks.length} stocks
            </td>
            <td colSpan={3} />
          </tr>
        </tfoot>
      </table>
    </div>
  );
});

// ---------------------------------------------------------------------------
// Group view
// ---------------------------------------------------------------------------

function groupByIndustry(stocks) {
  const map = new Map();
  for (const s of stocks) {
    const key = s.industry || "Other";
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(s);
  }
  return [...map.entries()]
    .map(([industry, items]) => ({ industry, items }))
    .sort((a, b) => b.items.length - a.items.length);
}

const GroupRow = memo(function GroupRow({ industry, items }) {
  const [open, setOpen] = useState(false);
  const tickers = items.map((s) => s.ticker);

  return (
    <div className="border-t border-zinc-800 first:border-t-0">
      <div
        className="group flex cursor-pointer items-center gap-2 px-3 py-2 hover:bg-zinc-800/40"
        onClick={() => setOpen((o) => !o)}
      >
        <span className="text-zinc-500 text-xs">{open ? "▾" : "▸"}</span>
        <span className="flex-1 text-sm font-medium text-zinc-200">{industry}</span>
        <span className="text-xs text-zinc-500">{items.length}</span>
        <span className="opacity-0 transition-opacity group-hover:opacity-100">
          <CopyButton tickers={tickers} />
        </span>
      </div>

      {open && (
        <div className="ml-4 border-l border-zinc-700 pb-1">
          {items.map((s) => (
            <div
              key={s.ticker}
              className="flex items-center gap-3 px-3 py-1 text-xs hover:bg-zinc-800/30"
            >
              <a
                href={`https://finviz.com/quote.ashx?t=${s.ticker}`}
                target="_blank"
                rel="noopener noreferrer"
                className="w-14 font-mono font-semibold text-cyan-400 hover:underline"
              >
                {s.ticker}
              </a>
              <span className="flex-1 truncate text-zinc-400">{s.company}</span>
              <span className="font-mono text-zinc-500">
                {s.adr_pct != null ? `${s.adr_pct.toFixed(1)}%` : "—"}
              </span>
              <span className={`w-16 text-right font-mono font-semibold ${changeCls(s.change_pct)}`}>
                {fmtPct(s.change_pct)}
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
});

const GroupView = memo(function GroupView({ stocks }) {
  const groups = groupByIndustry(stocks);

  if (!groups.length) {
    return <p className="py-12 text-center text-sm text-zinc-500">No groups to display.</p>;
  }

  return (
    <div>
      <div className="flex items-center gap-2 border-b border-zinc-800 px-3 py-1.5 text-xs font-medium text-zinc-600">
        <span className="flex-1">Industry</span>
        <span>Count</span>
      </div>
      {groups.map((g) => (
        <GroupRow key={g.industry} industry={g.industry} items={g.items} />
      ))}
    </div>
  );
});

// ---------------------------------------------------------------------------
// Main modal
// ---------------------------------------------------------------------------

const BreadthStockModal = memo(function BreadthStockModal({ filter, filterLabel, onClose }) {
  const [view, setView] = useState("list");
  const [stocks, setStocks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const abortRef = useRef(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    abortRef.current?.abort();
    const ctrl = new AbortController();
    abortRef.current = ctrl;

    try {
      const res = await fetch(
        `${process.env.PUBLIC_URL}/breadth_stocks_${filter}.json?_=${Date.now()}`,
        { signal: ctrl.signal }
      );
      if (!res.ok) throw new Error(`HTTP ${res.status} — stock list not found. Run breadth_stocks_builder.py first.`);
      const data = await res.json();
      setStocks(data.stocks ?? []);
    } catch (e) {
      if (e.name === "AbortError") return;
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }, [filter]);

  useEffect(() => {
    void load();
    return () => abortRef.current?.abort();
  }, [load]);

  // Close on Escape
  useEffect(() => {
    const handler = (e) => { if (e.key === "Escape") onClose(); };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onClose]);

  // Apply client-side guard for down scanners so only genuinely negative
  // stocks appear even if the pre-built JSON contains edge-case entries.
  const displayStocks = filter === "dn4"
    ? stocks.filter((s) => (s.change_pct ?? s.perf_1d ?? 0) <= -4)
    : stocks;

  const allTickers = displayStocks.map((s) => s.ticker);

  return (
    /* Backdrop */
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      {/* Panel */}
      <div className="relative flex h-[85vh] w-full max-w-3xl flex-col rounded-xl border border-zinc-700 bg-zinc-900 shadow-2xl">

        {/* Header */}
        <div className="flex items-center gap-3 border-b border-zinc-800 px-4 py-3">
          <div className="flex-1">
            <h2 className="text-sm font-semibold text-zinc-100">{filterLabel}</h2>
            {!loading && (
              <p className="text-xs text-zinc-500">
                {stocks.length} stocks · min $1B mkt cap
              </p>
            )}
          </div>

          {/* List / Group toggle */}
          <div className="flex items-center gap-1 rounded-lg border border-zinc-700 p-0.5">
            <button
              onClick={() => setView("list")}
              title="List view"
              className={`flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs transition-colors
                ${view === "list" ? "bg-zinc-700 text-zinc-100" : "text-zinc-400 hover:text-zinc-200"}`}
            >
              <LayoutList className="h-3.5 w-3.5" />
              List
            </button>
            <button
              onClick={() => setView("group")}
              title="Group by industry"
              className={`flex items-center gap-1.5 rounded-md px-2.5 py-1 text-xs transition-colors
                ${view === "group" ? "bg-zinc-700 text-zinc-100" : "text-zinc-400 hover:text-zinc-200"}`}
            >
              <Layers className="h-3.5 w-3.5" />
              Group
            </button>
          </div>

          {/* Copy all */}
          {allTickers.length > 0 && (
            <CopyButton tickers={allTickers} label="Copy" />
          )}

          {/* Close */}
          <button
            onClick={onClose}
            className="rounded p-1 text-zinc-500 hover:bg-zinc-700 hover:text-zinc-200"
            aria-label="Close"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Body */}
        <div className="min-h-0 flex-1 overflow-y-auto">
          {loading ? (
            <div className="flex h-full items-center justify-center">
              <Loader2 className="h-6 w-6 animate-spin text-zinc-500" />
            </div>
          ) : error ? (
            <div className="flex h-full flex-col items-center justify-center gap-2 text-sm text-rose-400 px-6 text-center">
              <p>{error}</p>
              <button
                onClick={() => void load()}
                className="mt-2 text-xs text-zinc-400 underline hover:text-zinc-200"
              >
                Retry
              </button>
            </div>
          ) : view === "list" ? (
            <ListView stocks={displayStocks} filter={filter} />
          ) : (
            <GroupView stocks={displayStocks} />
          )}
        </div>
      </div>
    </div>
  );
});

export default BreadthStockModal;
