/**
 * MarketBreadthMonitor.js
 *
 * Stockbee Market Monitor table for Power Theme.
 * Reads from /breadth_monitor.json (generated by breadth_monitor.py).
 *
 * Columns: DATE | UP 4%+ | DN 4%+ | 5D R | 10D R |
 *          UP 25% Q | DN 25% Q | UP 25% M | DN 25% M |
 *          UP 50% M | DN 50% M | UP 13% 34D | DN 13% 34D |
 *          10x ATR Ext | >50 DMA | Share Universe | T2108 | S&P
 */

import { memo, useCallback, useEffect, useRef, useState } from "react";
import { BarChart3, Check, Clipboard, Copy, Download, ExternalLink, RefreshCw, Sparkles, Trash2, X } from "lucide-react";
import BreadthStockModal from "./BreadthStockModal";

// ---------------------------------------------------------------------------
// Gemini config
// ---------------------------------------------------------------------------

const GEMINI_KEY      = process.env.REACT_APP_GEMINI_KEY || "";
const GEMINI_CACHE_NS = "sbmm_gemini_v9";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const BULLISH_FILTERS = new Set(["up4", "up25q", "up25m", "up50m", "up13_34", "above50dma"]);

// ---------------------------------------------------------------------------
// WatchlistClipboard panel
// ---------------------------------------------------------------------------

const WatchlistClipboard = memo(function WatchlistClipboard({ groups, onRemoveGroup, onClear, onClose }) {
  const [tab, setTab]       = useState("bullish");
  const [copied, setCopied] = useState(false);
  const timerRef            = useRef(null);

  const bullish = groups.filter((g) => g.sentiment === "bullish");
  const bearish = groups.filter((g) => g.sentiment === "bearish");
  const active  = tab === "bullish" ? bullish : bearish;

  const allTickers = active.flatMap((g) => g.tickers);
  const uniqueTickers = [...new Set(allTickers)];

  const handleCopy = () => {
    if (!uniqueTickers.length) return;
    navigator.clipboard.writeText(uniqueTickers.join(",")).then(() => {
      setCopied(true);
      clearTimeout(timerRef.current);
      timerRef.current = setTimeout(() => setCopied(false), 1800);
    });
  };

  const handleDownload = () => {
    if (!uniqueTickers.length) return;
    const csv = "Ticker\n" + uniqueTickers.join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href = url; a.download = `${tab}_tickers.csv`; a.click();
    URL.revokeObjectURL(url);
  };

  useEffect(() => () => clearTimeout(timerRef.current), []);

  return (
    <div className="absolute right-0 top-full mt-1 z-50 w-80 rounded-xl border border-zinc-700 bg-zinc-900 shadow-2xl">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-zinc-800 px-3 py-2">
        <span className="text-xs font-semibold text-zinc-300">Watchlist Clipboard</span>
        <button onClick={onClose} className="rounded p-0.5 text-zinc-500 hover:text-zinc-200">
          <X className="h-3.5 w-3.5" />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex gap-1 border-b border-zinc-800 px-3 py-2">
        <button
          onClick={() => setTab("bullish")}
          className={`rounded-full px-3 py-0.5 text-xs font-medium transition-colors
            ${tab === "bullish" ? "bg-emerald-600 text-white" : "bg-zinc-800 text-zinc-400 hover:text-zinc-200"}`}
        >
          Bullish ({bullish.reduce((s, g) => s + g.tickers.length, 0)})
        </button>
        <button
          onClick={() => setTab("bearish")}
          className={`rounded-full px-3 py-0.5 text-xs font-medium transition-colors
            ${tab === "bearish" ? "bg-rose-600 text-white" : "bg-zinc-800 text-zinc-400 hover:text-zinc-200"}`}
        >
          Bearish ({bearish.reduce((s, g) => s + g.tickers.length, 0)})
        </button>
      </div>

      {/* Groups */}
      <div className="max-h-56 overflow-y-auto">
        {active.length === 0 ? (
          <p className="py-6 text-center text-xs text-zinc-600">No {tab} tickers yet.</p>
        ) : (
          active.map((g) => (
            <div key={g.id} className="border-b border-zinc-800/60 px-3 py-2">
              {/* Group label row */}
              <div className="flex items-center justify-between mb-1">
                <span className="text-xs font-semibold text-zinc-200">{g.label}</span>
                <div className="flex items-center gap-2">
                  <span className="text-xs text-zinc-500">{g.tickers.length}</span>
                  <button
                    onClick={() => onRemoveGroup(g.id)}
                    className="text-zinc-600 hover:text-rose-400 transition-colors"
                  >
                    <X className="h-3 w-3" />
                  </button>
                </div>
              </div>
              {/* Tickers text */}
              <p className="text-[11px] leading-relaxed text-zinc-400 break-all">
                {g.tickers.join(",")}
              </p>
            </div>
          ))
        )}
      </div>

      {/* Footer actions */}
      <div className="flex items-center justify-between border-t border-zinc-800 px-3 py-2">
        <button
          onClick={handleCopy}
          className="flex items-center gap-1 text-xs text-zinc-400 hover:text-zinc-200 transition-colors"
        >
          {copied ? <Check className="h-3 w-3 text-emerald-400" /> : <Copy className="h-3 w-3" />}
          {copied ? "Copied!" : "Copy"}
        </button>
        <button
          onClick={handleDownload}
          className="flex items-center gap-1 text-xs text-zinc-400 hover:text-zinc-200 transition-colors"
        >
          <Download className="h-3 w-3" />
          Download CSV
        </button>
        <button
          onClick={() => onClear(tab)}
          className="flex items-center gap-1 text-xs text-zinc-400 hover:text-rose-400 transition-colors"
        >
          <Trash2 className="h-3 w-3" />
          Clear
        </button>
      </div>
    </div>
  );
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function fmtN(n) {
  if (n == null || !Number.isFinite(n)) return "—";
  return Number.isInteger(n) ? String(n) : n.toFixed(2);
}

function t2108Badge(v) {
  if (v == null || !Number.isFinite(v)) return null;
  if (v >= 80) return { label: "Extreme Overbought (≥80%)", cls: "bg-red-900/60 text-red-300" };
  if (v >= 70) return { label: "Overbought (≥70%)",         cls: "bg-amber-900/60 text-amber-300" };
  if (v <= 20) return { label: "Extreme Oversold (≤20%)",   cls: "bg-cyan-900/60 text-cyan-300" };
  if (v <= 30) return { label: "Oversold (≤30%)",           cls: "bg-emerald-900/60 text-emerald-300" };
  return { label: "Neutral (30–70%)", cls: "bg-slate-700/60 text-slate-300" };
}

// ---------------------------------------------------------------------------
// Loading skeleton
// ---------------------------------------------------------------------------

const Skeleton = memo(function Skeleton() {
  return (
    <div className="rounded-xl border border-gray-800 bg-gray-900 p-4">
      <div className="mb-3 h-5 w-48 animate-pulse rounded bg-gray-700" />
      <div className="space-y-2">
        {[...Array(6)].map((_, i) => (
          <div key={i} className="h-6 animate-pulse rounded bg-gray-800" />
        ))}
      </div>
    </div>
  );
});

// ---------------------------------------------------------------------------
// Analysis badge
// ---------------------------------------------------------------------------

const Badge = memo(function Badge({ label, variant }) {
  const cls = {
    "Extreme Bullish": "bg-emerald-900/70 text-emerald-300 border-emerald-700",
    Bullish:           "bg-emerald-900/40 text-emerald-400 border-emerald-800",
    Caution:           "bg-amber-900/40  text-amber-400  border-amber-800",
    Bearish:           "bg-rose-900/40   text-rose-400   border-rose-800",
    Neutral:           "bg-slate-800     text-slate-400  border-slate-700",
    Oversold:          "bg-rose-900/60   text-rose-300   border-rose-700",
    Overbought:        "bg-amber-900/60  text-amber-300  border-amber-700",
  }[variant] ?? "bg-slate-800 text-slate-400 border-slate-700";

  return (
    <span className={`inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium ${cls}`}>
      {label}
    </span>
  );
});

// ---------------------------------------------------------------------------
// Analysis panel (derived from the latest row)
// ---------------------------------------------------------------------------

const AnalysisPanel = memo(function AnalysisPanel({ row }) {
  if (!row) return null;

  const up4 = row.up_4_pct ?? 0;
  const dn4 = row.down_4_pct ?? 0;
  const thrust = dn4 <= 0 ? up4 > 0 : up4 > 3 * dn4;

  const shortTerm = thrust
    ? { label: "Extremely Bullish / Thrust", badge: "Extreme Bullish" }
    : up4 > dn4
    ? { label: "Bulls leading on the 4%+ tape", badge: "Bullish" }
    : { label: "Bears competitive on the 4%+ tape", badge: "Caution" };

  const upQ = row.up_25_q, dnQ = row.down_25_q;
  const quarterly =
    upQ != null && dnQ != null && dnQ > upQ
      ? { label: "Quarterly breadth skewed negative (dn > up)", badge: "Bearish" }
      : { label: "Quarterly breadth not dominated by losers", badge: "Neutral" };

  const t = t2108Badge(row.t2108);

  return (
    <div className="flex flex-wrap gap-3">
      <div className="flex items-center gap-2 text-xs text-slate-400">
        <span>Short-term:</span>
        <Badge label={shortTerm.badge} variant={shortTerm.badge} />
        <span className="text-slate-500">{shortTerm.label}</span>
      </div>
      <div className="flex items-center gap-2 text-xs text-slate-400">
        <span>Quarterly:</span>
        <Badge label={quarterly.badge} variant={quarterly.badge} />
        <span className="text-slate-500">{quarterly.label}</span>
      </div>
      {t && (
        <div className="flex items-center gap-2 text-xs text-slate-400">
          <span>T2108:</span>
          <Badge label={t.label} variant={t.label.startsWith("Over") ? (t.label.includes("sold") ? "Oversold" : "Overbought") : "Neutral"} />
        </div>
      )}
    </div>
  );
});

// ---------------------------------------------------------------------------
// Gemini Breadth Read — Stockbee-style AI analysis of the last 20 rows
// ---------------------------------------------------------------------------

const STOCKBEE_CONTEXT = `
You are analysing market breadth data the way Pradeep Bonde (Stockbee) would read it.
Stockbee's colour thresholds for notable readings:
  - Up 4%+  ≥400 = healthy buying thrust; ≥600 = extreme thrust (very bullish)
  - Down 4%+ ≥200 = distribution pressure; ≥400 = heavy selling (bearish)
  - 5D / 10D Ratio: ≥2.0 = strong bull trend; ≥1.5 = bullish; ≤0.5 = bearish; ≤0.3 = very bearish
  - Up 25% Quarterly: rising count = momentum universe expanding (bullish)
  - Down 25% Quarterly: rising count = momentum breaking down
  - Up 25% Monthly: broad participation; high = bull trend healthy
  - Down 25% Monthly: rising = distribution broadening
  - Up 50% Monthly ≥50 = hot market; ≥100 = frothy / extended (caution signal, not bullish)
  - Down 50% Monthly ≥30 = panic / washout (watch for reversal)
  - Up 13% 34-Day: medium-term momentum; acceleration = stage-2 breakouts firing
  - Down 13% 34-Day: rising = intermediate downtrend widening
  - 10x ATR Ext ≥20 = market getting extended (amber warning); ≥50 = extreme extension (deep amber — fade risk)
  - % above 50 DMA < 30% = oversold / bearish; > 80% = extended / overbought; 40–70% = healthy bull
  - T2108 ≤20 = deeply oversold — historical buy signal (cyan); ≥80 = overbought warning
`.trim();

async function callGemini(rows) {
  if (!GEMINI_KEY) return null;
  // Send last 20 rows, most-recent first, trimmed to essential fields
  const snapshot = rows.slice(0, 20).map(r => ({
    date:        r.date,
    up4:         r.up_4_pct,
    dn4:         r.down_4_pct,
    r5d:         r.ratio_5d,
    r10d:        r.ratio_10d,
    up25q:       r.up_25_q,
    dn25q:       r.down_25_q,
    up25m:       r.up_25_m,
    dn25m:       r.down_25_m,
    up50m:       r.up_50_m,
    dn50m:       r.down_50_m,
    up13:        r.up_13_34d,
    dn13:        r.down_13_34d,
    atrExt:      r.atr_10x_ext,
    above50dma:  r.above_50dma_pct,
    t2108:       r.t2108,
    sp:          r.sp_index,
  }));

  const prompt = `${STOCKBEE_CONTEXT}

Below is the last 20 trading sessions of Stockbee Market Monitor data (newest row first).
Fields: date | up4 | dn4 | 5d-ratio | 10d-ratio | up25Q | dn25Q | up25M | dn25M | up50M | dn50M | up13_34d | dn13_34d | atrExt | %above50dma | T2108 | S&P

${JSON.stringify(snapshot, null, 0)}

Reply with ONLY the 4 bullet points below — no intro, no outro, no markdown headers.
Each bullet: bold ALL-CAPS label + em-dash + 2 concise sentences with specific numbers.

**TODAY** — (today's up4/dn4 absolute counts and ratio; note any threshold crossing per the colour rules above)
**WEEK** — (5-day trend in the ratio and up25M or up13_34d; is breadth improving, steady, or fading?)
**MONTH** — (up50M froth level, % above 50dma zone, T2108 reading; what it means for swing traders)
**REGIME** — (one-word regime label + what Stockbee would watch as the next leading signal)`;

  const url  = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${GEMINI_KEY}`;
  const body = {
    contents: [{ parts: [{ text: prompt }] }],
    generationConfig: {
      temperature: 0.35,
      maxOutputTokens: 2048,
      thinkingConfig: { thinkingBudget: 0 },   // inside generationConfig — disables thinking chain
    },
  };
  const res  = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const json = await res.json();

  // Surface API-level errors so they appear in the UI instead of silently showing "Awaiting data…"
  if (json?.error) throw new Error(`Gemini API: ${json.error.message ?? JSON.stringify(json.error)}`);
  if (!json?.candidates?.length) throw new Error(`Gemini returned no candidates. Response: ${JSON.stringify(json).slice(0, 200)}`);

  // gemini-2.5-flash (thinking model) returns multiple parts:
  //   { thought: true, text: "…chain-of-thought…" }   ← skip
  //   { text: "**TODAY** — …" }                        ← this is the answer
  const parts = json.candidates[0].content?.parts ?? [];
  const textPart = parts.find(p => !p.thought) ?? parts[0];
  return textPart?.text?.trim() ?? null;
}

/**
 * Parse the 4-bullet Gemini response into structured objects.
 * Line-by-line approach — tolerates any dash variant and trailing continuation lines.
 * Matches: **LABEL** — text   or   **LABEL**: text   or   LABEL — text
 */
function parseBullets(raw) {
  if (!raw) return null;
  const bullets = [];
  let current = null;
  for (const line of raw.split(/\r?\n/)) {
    // Header line: **TODAY** — …  /  **WEEK**: …  /  TODAY — …
    const m = line.match(/^\*{0,2}([A-Z]{3,8})\*{0,2}\s*[—–:\-]+\s*(.*)/);
    if (m && ["TODAY","WEEK","MONTH","REGIME"].includes(m[1])) {
      if (current) bullets.push(current);
      current = { label: m[1], text: m[2].trim() };
    } else if (current && line.trim()) {
      current.text += " " + line.trim();
    }
  }
  if (current) bullets.push(current);
  if (bullets.length < 2) return null;
  // Strip any stray **bold** markers Gemini embeds inside the text
  return bullets.map(b => ({ ...b, text: b.text.replace(/\*\*/g, "").trim() }));
}

const LABEL_COLOR = {
  TODAY:  "text-sky-400",
  WEEK:   "text-violet-400",
  MONTH:  "text-amber-400",
  REGIME: "text-emerald-400",
};

/**
 * GeminiBreadthRead
 *
 * Priority order for the analysis text:
 *   1. data.gemini_analysis — pre-computed by breadth_monitor.py at scrape time (preferred)
 *   2. localStorage cache   — from a previous browser-side call
 *   3. Live Gemini call     — fallback if both above are absent and GEMINI_KEY is set
 *
 * This means on most loads the text appears instantly from the JSON with no API call.
 * The "↻ refresh" button forces a fresh live call regardless.
 */
const GeminiBreadthRead = memo(function GeminiBreadthRead({ rows, precomputedAnalysis }) {
  const [text,    setText]    = useState(() => precomputedAnalysis || null);
  const [loading, setLoading] = useState(false);
  const [error,   setError]   = useState(null);
  const latestDate = rows?.[0]?.date ?? "";

  const cacheKey = `${GEMINI_CACHE_NS}_${latestDate}`;

  const run = useCallback(async (force = false) => {
    // 1. Use pre-computed analysis from the JSON (always preferred)
    if (!force && precomputedAnalysis) { setText(precomputedAnalysis); return; }
    // 2. Check localStorage cache
    if (!force) {
      try {
        const cached = JSON.parse(localStorage.getItem(cacheKey) ?? "null");
        if (cached?.text) { setText(cached.text); return; }
      } catch { /* ignore */ }
    }
    // 3. Live Gemini call (fallback / forced refresh)
    if (!GEMINI_KEY || !rows?.length) return;
    setLoading(true);
    setError(null);
    try {
      const result = await callGemini(rows);
      if (result) {
        setText(result);
        try { localStorage.setItem(cacheKey, JSON.stringify({ text: result })); } catch { /* quota */ }
      }
    } catch (e) {
      setError(e.message ?? "Gemini request failed");
    } finally {
      setLoading(false);
    }
  }, [rows, cacheKey, precomputedAnalysis]);

  useEffect(() => { void run(false); }, [run]);

  // Show even without GEMINI_KEY if pre-computed text is available
  if (!precomputedAnalysis && !GEMINI_KEY) return null;

  const bullets = parseBullets(text);

  return (
    <div className="border-b border-gray-800 px-4 py-3">
      {/* Header row */}
      <div className="flex items-center gap-2 mb-2.5">
        <Sparkles className="h-3.5 w-3.5 text-violet-400 flex-shrink-0" />
        <span className="text-[11px] font-bold text-zinc-400 uppercase tracking-wider">
          Gemini · Stockbee Breadth Read
        </span>
        {loading && <RefreshCw size={10} className="text-zinc-500 animate-spin ml-1" />}
        <button
          onClick={() => run(true)}
          disabled={loading}
          title="Re-run analysis"
          className="ml-auto text-[10px] text-zinc-600 hover:text-zinc-300 disabled:opacity-40 transition-colors"
        >
          {loading ? "thinking…" : "↻ refresh"}
        </button>
      </div>

      {/* Body */}
      {error && (
        <p className="text-[11px] text-rose-400/80 italic">{error}</p>
      )}

      {!error && !text && !loading && (
        <p className="text-[11px] text-zinc-600 italic">Awaiting data…</p>
      )}

      {!error && loading && !text && (
        <div className="space-y-1.5">
          {[80, 65, 72, 58].map((w, i) => (
            <div key={i} className="h-3 rounded bg-zinc-800 animate-pulse" style={{ width: `${w}%` }} />
          ))}
        </div>
      )}

      {/* Structured bullets */}
      {!error && text && bullets && (
        <ol className="space-y-1.5">
          {bullets.map(({ label, text: body }) => (
            <li key={label} className="flex gap-2 text-[12px] leading-relaxed">
              <span className={`flex-shrink-0 font-bold text-[11px] uppercase tracking-wide pt-[1px] w-14 ${LABEL_COLOR[label] ?? "text-zinc-400"}`}>
                {label}
              </span>
              <span className="text-zinc-200">{body}</span>
            </li>
          ))}
        </ol>
      )}

      {/* Fallback: raw text if parser couldn't split bullets */}
      {!error && text && !bullets && (
        <p className="text-[12px] text-zinc-200 leading-relaxed whitespace-pre-wrap break-words">{text}</p>
      )}
    </div>
  );
});

// ---------------------------------------------------------------------------
// Clickable column map — all rows
// ---------------------------------------------------------------------------

const CLICKABLE_COLS = {
  up_4_pct:    { filter: "up4",     label: "Up 4%+ Today" },
  down_4_pct:  { filter: "dn4",     label: "Down 4%+ Today" },
  up_25_q:     { filter: "up25q",   label: "Up 25%+ Quarterly" },
  down_25_q:   { filter: "dn25q",   label: "Down 25%+ Quarterly" },
  up_25_m:     { filter: "up25m",   label: "Up 25%+ Monthly" },
  down_25_m:   { filter: "dn25m",   label: "Down 25%+ Monthly" },
  up_50_m:     { filter: "up50m",   label: "Up 50%+ Monthly" },
  down_50_m:   { filter: "dn50m",   label: "Down 50%+ Monthly" },
  up_13_34d:   { filter: "up13_34", label: "Up 13%+ 34-Day" },
  down_13_34d: { filter: "dn13_34", label: "Down 13%+ 34-Day" },
};

// ---------------------------------------------------------------------------
// Cell color helpers — mirrors Stockbee Market Monitor conditional formatting
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Color palette — verified against Google Sheet CSS class extraction:
//   s7  (rgb 244,204,204) light pink  → text-rose-400          (down-day, sub-threshold)
//   s8  (rgb 0,255,0)     bright green → bg-green-600 text-white (bullish)
//   s9  (rgb 224,102,102) coral red   → bg-red-600 text-white   (bearish)
//   s10 (rgb 51,153,102)  medium green → bg-green-800 text-white (strong thrust, UP day ≥300)
//   s6  white/neutral     → ""                                   (no highlight)
//
// Primary pair (Up4/Down4): 3-tier 2D matrix — direction AND value at threshold 300
// Secondary pairs (quarterly/monthly 25%/34-day): pure binary, direction only
// Monthly 50%: standalone contrarian — Up50m ≥20 = red froth; Dn50m ≥20 = green oversold
// Ratios: standalone — ≥2.0 green, ≤0.50 red
// ---------------------------------------------------------------------------
const S7  = "bg-rose-400 text-white font-semibold";
const S8  = "bg-green-600 text-white font-semibold";
const S9  = "bg-red-600 text-white font-semibold";
const S10 = "bg-green-800 text-white font-semibold";

// Up 4%+: UP day → s8 (<300) or s10 (≥300); DOWN day → always s7
function clsUp4(v, netPos) {
  if (v == null) return "";
  return netPos ? (v >= 300 ? S10 : S8) : S7;
}
// Down 4%+: UP day → always s8; DOWN day → s7 (<300) or s9 (≥300)
function clsDn4(v, netPos) {
  if (v == null) return "";
  return netPos ? S8 : (v >= 300 ? S9 : S7);
}
// Ratios: standalone — green ≥2.0, red ≤0.50, neutral otherwise
function clsRatio(v) {
  if (v == null) return "";
  if (v >= 2.0)  return S8;
  if (v <= 0.50) return S9;
  return "";
}
// Quarterly pair: pure binary — both columns reflect which side dominates
function clsUp25q(v, pairPos) { return v == null ? "" : (pairPos ? S8 : S9); }
function clsDn25q(v, pairPos) { return v == null ? "" : (pairPos ? S8 : S9); }
// Monthly 25% pair: pure binary
function clsUp25m(v, pairPos) { return v == null ? "" : (pairPos ? S8 : S9); }
function clsDn25m(v, pairPos) { return v == null ? "" : (pairPos ? S8 : S9); }
// Up 50% Monthly: standalone red warning (parabolic froth) when ≥20
function clsUp50m(v) { return (v == null || v < 20) ? "" : S9; }
// Down 50% Monthly: standalone green (oversold contrarian) when ≥20
function clsDn50m(v) { return (v == null || v < 20) ? "" : S8; }
// 34-Day pair: pure binary
function clsUp13(v, pairPos) { return v == null ? "" : (pairPos ? S8 : S9); }
function clsDn13(v, pairPos) { return v == null ? "" : (pairPos ? S8 : S9); }
// 10x ATR Ext: s5=yellow warning at ≥20, deeper yellow at ≥50
function clsAtrExt(v, clickable) {
  const click = clickable ? "cursor-pointer underline decoration-dotted underline-offset-2" : "";
  if (v == null)  return `text-purple-300 ${click}`;
  if (v >= 50)    return `bg-yellow-500 text-black font-bold ${click}`;
  if (v >= 20)    return `bg-yellow-800 text-yellow-200 font-semibold ${click}`;
  return `text-purple-300 ${click}`;
}
// >50 DMA: s9=red below 30%, s8=green above 80%
function clsAbove50dma(v, clickable) {
  const click = clickable ? "cursor-pointer underline decoration-dotted underline-offset-2" : "";
  if (v == null) return `text-sky-300 ${click}`;
  if (v < 20)    return `bg-red-700 text-white font-bold ${click}`;
  if (v < 30)    return `bg-red-900 text-red-100 font-semibold ${click}`;
  if (v >= 90)   return `bg-green-600 text-white font-semibold ${click}`;
  if (v >= 80)   return `bg-green-800 text-green-100 ${click}`;
  return `text-sky-300 ${click}`;
}
// T2108: s4=cyan oversold ≤20 (best buy signal), s5=yellow overbought ≥80
function clsT2108(v) {
  if (v == null) return "text-amber-300";
  if (v <= 20)   return "bg-cyan-700 text-white font-semibold";
  if (v >= 80)   return "bg-yellow-600 text-black font-semibold";
  return "text-amber-300";
}

// ---------------------------------------------------------------------------
// ColTip — column header with hover tooltip showing color-coded thresholds
// ---------------------------------------------------------------------------

const ColTip = memo(function ColTip({ children, tiers, width = "w-60" }) {
  return (
    <div className="relative group/tip cursor-help">
      {children}
      {/* Tooltip card — appears below the header, above the data rows */}
      <div className={`absolute hidden group-hover/tip:block z-[9999] top-full left-1/2 -translate-x-1/2
                       mt-1 ${width} rounded-lg bg-zinc-950 border border-zinc-700 p-2.5 text-left
                       shadow-2xl pointer-events-none`}>
        {tiers.map((t, idx) => (
          <div key={idx} className="flex items-start gap-1.5 mb-1 last:mb-0">
            <span className={`mt-[3px] w-2.5 h-2.5 flex-shrink-0 rounded-sm border border-white/10 ${t.swatch}`} />
            <span className="text-[10px] text-zinc-300 leading-tight whitespace-normal">{t.desc}</span>
          </div>
        ))}
      </div>
    </div>
  );
});

// ---------------------------------------------------------------------------
// Main table
// ---------------------------------------------------------------------------

const BreadthTable = memo(function BreadthTable({ rows, latestDate, onOpenModal }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[1040px] border-collapse text-left">
        <caption className="sr-only">Stockbee Market Monitor breadth history.</caption>
        <thead>
          {/* ── Row 1: group headers ────────────────────────────── */}
          <tr>
            <th rowSpan={2}
                className="sticky left-0 z-10 bg-amber-500 text-black text-xs font-bold px-2 py-1 text-center whitespace-nowrap border border-amber-600 align-middle">
              Date
            </th>
            <th colSpan={4} className="bg-amber-400 text-black text-xs font-bold px-1 py-1 text-center border border-amber-500">
              Primary Breadth Indicators
            </th>
            <th colSpan={8} className="bg-emerald-500 text-black text-xs font-bold px-1 py-1 text-center border border-emerald-600">
              Secondary Breadth Indicators
            </th>
            {/* 10x ATR Ext — rowSpan=2 with tooltip */}
            <th rowSpan={2} className="bg-amber-400 text-black text-[10px] font-bold px-1 py-1 text-center border border-amber-500 align-middle">
              <ColTip tiers={[
                { swatch: "bg-amber-700",  desc: "≥ 50 — EXTREME. Many stocks far from 50-day MA. Sharp pullback likely. Reduce new longs." },
                { swatch: "bg-amber-950",  desc: "≥ 20 — Extended. Market stretched; new entries risky." },
                { swatch: "bg-zinc-700",   desc: "< 20 — Normal extension range." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"10x ATR\nExt."}</div>
              </ColTip>
            </th>
            {/* >50dma — rowSpan=2 with tooltip */}
            <th rowSpan={2} className="bg-sky-400 text-black text-[10px] font-bold px-1 py-1 text-center border border-sky-500 align-middle">
              <ColTip tiers={[
                { swatch: "bg-emerald-600", desc: "≥ 90% — Extremely healthy bull. Broad participation across all stocks." },
                { swatch: "bg-emerald-900", desc: "≥ 80% — Healthy bull market. Safe to be fully invested." },
                { swatch: "bg-zinc-700",    desc: "30–80% — Neutral range." },
                { swatch: "bg-rose-900",    desc: "< 30% — Bear territory. Most stocks below 50-day MA." },
                { swatch: "bg-rose-700",    desc: "< 20% — Capitulation zone. Historically marks major market bottoms." },
              ]}>
                {">50dma"}
              </ColTip>
            </th>
            {/* Stock Universe $1B+ — no tooltip (just a count) */}
            <th rowSpan={2} className="bg-violet-400 text-black font-bold px-1 py-1 text-center border border-violet-500 align-middle">
              <div className="text-[10px]">Stock Universe</div>
              <div className="text-[8px] font-normal">Mkt Cap &gt; $1B</div>
            </th>
            {/* Stock Universe (Worden) — no tooltip */}
            <th rowSpan={2} className="bg-violet-400 text-black text-[10px] font-bold px-1 py-1 text-center whitespace-pre-line border border-violet-500 align-middle leading-tight">
              {"Stock\nUniverse"}
            </th>
            {/* T2108 — rowSpan=2 with tooltip */}
            <th rowSpan={2} className="bg-amber-400 text-black text-[10px] font-bold px-1 py-1 text-center border border-amber-500 align-middle">
              <ColTip tiers={[
                { swatch: "bg-amber-900", desc: "≥ 80% — Overbought. Market extended; expect consolidation or pullback." },
                { swatch: "bg-zinc-700",  desc: "30–80% — Neutral zone." },
                { swatch: "bg-cyan-900",  desc: "≤ 20% — OVERSOLD (teal). Best buy signal. Historically marks major bottoms — highest risk/reward for new longs." },
              ]}>
                T2108
              </ColTip>
            </th>
            <th rowSpan={2} className="bg-amber-400 text-black text-[10px] font-bold px-1 py-1 text-center whitespace-nowrap border border-amber-500 align-middle">
              S&amp;P
            </th>
          </tr>

          {/* ── Row 2: sub-headers with ColTip on each ─────────── */}
          <tr className="border-b border-gray-700">
            {/* Stocks Up 4%+ */}
            <th className="bg-amber-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-amber-400">
              <ColTip tiers={[
                { swatch: "bg-green-800",  desc: "UP day + ≥ 300 — Strong breadth thrust. Broad institutional buying across the market." },
                { swatch: "bg-green-600",  desc: "UP day + < 300 — Positive breadth. Bulls in control; safe to hold longs." },
                { swatch: "text-rose-400 border border-rose-400", desc: "DOWN day — Bears winning the 4% tape regardless of count." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"Stocks Up\n4%+ Today"}</div>
              </ColTip>
            </th>
            {/* Stocks Down 4%+ */}
            <th className="bg-amber-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-amber-400">
              <ColTip tiers={[
                { swatch: "bg-red-600",   desc: "DOWN day + ≥ 300 — Panic / capitulation. Extreme fear; can mark a short-term bottom." },
                { swatch: "text-rose-400 border border-rose-400", desc: "DOWN day + < 300 — Elevated selling, but not extreme." },
                { swatch: "bg-green-600", desc: "UP day — Down count is low; bulls dominate." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"Stocks Down\n4%+ Today"}</div>
              </ColTip>
            </th>
            {/* 5 Day Ratio */}
            <th className="bg-amber-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-amber-400">
              <ColTip tiers={[
                { swatch: "bg-green-600", desc: "≥ 2.0 — Strongly bullish 5-day tape. Stay fully long." },
                { swatch: "bg-zinc-700",  desc: "0.5–2.0 — Neutral range." },
                { swatch: "bg-red-600",   desc: "≤ 0.50 — Bearish 5-day tape. Reduce exposure." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"5 Day\nRatio"}</div>
              </ColTip>
            </th>
            {/* 10 Day Ratio */}
            <th className="bg-amber-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-amber-400">
              <ColTip tiers={[
                { swatch: "bg-green-600", desc: "≥ 2.0 — Strongly bullish 10-day tape. Stay fully long." },
                { swatch: "bg-zinc-700",  desc: "0.5–2.0 — Neutral range." },
                { swatch: "bg-red-600",   desc: "≤ 0.50 — Bearish 10-day tape. Reduce exposure." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"10 Day\nRatio"}</div>
              </ColTip>
            </th>
            {/* Up 25%+ Quarter */}
            <th className="bg-emerald-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-emerald-400">
              <ColTip tiers={[
                { swatch: "bg-green-600", desc: "Up25q > Down25q — Quarterly breadth positive. Pair turns GREEN; bull market structural." },
                { swatch: "bg-red-600",   desc: "Down25q > Up25q — Quarterly breadth negative. Pair turns RED; bear market structural." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"Stocks Up\n25%+ in a\nQuarter"}</div>
              </ColTip>
            </th>
            {/* Down 25%+ Quarter */}
            <th className="bg-emerald-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-emerald-400">
              <ColTip tiers={[
                { swatch: "bg-green-600", desc: "Up25q > Down25q — Both quarterly columns show green (pair is bullish)." },
                { swatch: "bg-red-600",   desc: "Down25q > Up25q — Both quarterly columns show red (pair is bearish)." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"Stocks Down\n25%+ in a\nQuarter"}</div>
              </ColTip>
            </th>
            {/* Up 25%+ Month */}
            <th className="bg-emerald-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-emerald-400">
              <ColTip tiers={[
                { swatch: "bg-green-600", desc: "Up25m > Down25m — Monthly breadth positive. Pair turns GREEN." },
                { swatch: "bg-red-600",   desc: "Down25m > Up25m — Monthly breadth negative. Pair turns RED." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"Stocks Up\n25%+ in a\nMonth"}</div>
              </ColTip>
            </th>
            {/* Down 25%+ Month */}
            <th className="bg-emerald-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-emerald-400">
              <ColTip tiers={[
                { swatch: "bg-green-600", desc: "Up25m > Down25m — Both monthly columns show green (pair is bullish)." },
                { swatch: "bg-red-600",   desc: "Down25m > Up25m — Both monthly columns show red (pair is bearish)." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"Stocks Down\n25%+ in a\nMonth"}</div>
              </ColTip>
            </th>
            {/* Up 50%+ Month */}
            <th className="bg-emerald-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-emerald-400">
              <ColTip tiers={[
                { swatch: "bg-red-600",  desc: "≥ 20 — PARABOLIC FROTH WARNING. Many stocks up 50%+ in a month = speculation extreme. Reduce risk." },
                { swatch: "bg-zinc-700", desc: "< 20 — Normal. No parabolic froth." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"Stocks Up\n50%+ in a\nMonth"}</div>
              </ColTip>
            </th>
            {/* Down 50%+ Month */}
            <th className="bg-emerald-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-emerald-400">
              <ColTip tiers={[
                { swatch: "bg-green-600", desc: "≥ 20 — OVERSOLD CONTRARIAN SIGNAL. Many stocks down 50%+ = extreme washout. Look for bottom." },
                { swatch: "bg-zinc-700",  desc: "< 20 — Normal." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"Stocks Down\n50%+ in a\nMonth"}</div>
              </ColTip>
            </th>
            {/* Up 13%+ 34 Days */}
            <th className="bg-emerald-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-emerald-400">
              <ColTip tiers={[
                { swatch: "bg-green-600", desc: "Up13 > Down13 — 34-day breadth positive. Pair turns GREEN; medium-term momentum bullish." },
                { swatch: "bg-red-600",   desc: "Down13 > Up13 — 34-day breadth negative. Pair turns RED; medium-term momentum bearish." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"Stocks Up\n13%+ in\n34 Days"}</div>
              </ColTip>
            </th>
            {/* Down 13%+ 34 Days */}
            <th className="bg-emerald-300 text-black text-[10px] font-semibold px-1 py-1 text-center border border-emerald-400">
              <ColTip tiers={[
                { swatch: "bg-green-600", desc: "Up13 > Down13 — Both 34-day columns show green (pair is bullish)." },
                { swatch: "bg-red-600",   desc: "Down13 > Up13 — Both 34-day columns show red (pair is bearish)." },
              ]}>
                <div className="leading-tight whitespace-pre-line">{"Stocks Down\n13%+ in\n34 Days"}</div>
              </ColTip>
            </th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => {
            const isLatest = r.date === latestDate;
            // Each column pair uses its own net-delta to determine green/red palette
            const netPos    = r.up_4_pct   != null && r.down_4_pct   != null ? r.up_4_pct   > r.down_4_pct   : true;
            const pairPosQ  = r.up_25_q    != null && r.down_25_q    != null ? r.up_25_q    > r.down_25_q    : netPos;
            const pairPosM  = r.up_25_m    != null && r.down_25_m    != null ? r.up_25_m    > r.down_25_m    : netPos;
            const pairPos34 = r.up_13_34d  != null && r.down_13_34d  != null ? r.up_13_34d  > r.down_13_34d  : netPos;
            const bearish   = !netPos;

            // Clickable cell wrapper
            const cell = (field, content, colorCls = "") => {
              const col = CLICKABLE_COLS[field];
              if (col) {
                return (
                  <td
                    className={`px-1 py-1 text-right whitespace-nowrap cursor-pointer
                      underline decoration-dotted underline-offset-2 hover:brightness-125 ${colorCls}`}
                    onClick={() => onOpenModal(col.filter, col.label, r.date, isLatest)}
                    title={`View ${col.label} stocks — ${r.date_display}`}
                  >
                    {content}
                  </td>
                );
              }
              return <td className={`px-1 py-1 text-right whitespace-nowrap ${colorCls}`}>{content}</td>;
            };

            return (
              <tr
                key={r.date}
                className={`border-b border-gray-800/80 font-mono text-xs ${
                  isLatest ? "bg-gray-800/30" : ""
                } ${bearish ? "text-rose-200/70" : "text-slate-300"}`}
              >
                {/* DATE — sticky */}
                <td className="sticky left-0 z-10 bg-gray-900 py-1 pr-3 font-mono text-xs whitespace-nowrap">
                  {isLatest
                    ? <span className="font-semibold text-emerald-400">{r.date_display}</span>
                    : r.date_display}
                </td>

                {/* Primary Breadth ── ── ── ── ── ── ── ── ── ── ── ── ── */}
                {cell("up_4_pct",   fmtN(r.up_4_pct),   clsUp4(r.up_4_pct,   netPos))}
                {cell("down_4_pct", fmtN(r.down_4_pct), clsDn4(r.down_4_pct, netPos))}
                <td className={`px-1 py-1 text-right whitespace-nowrap ${clsRatio(r.ratio_5d)}`}>
                  {fmtN(r.ratio_5d)}
                </td>
                <td className={`px-1 py-1 text-right whitespace-nowrap ${clsRatio(r.ratio_10d)}`}>
                  {fmtN(r.ratio_10d)}
                </td>

                {/* Secondary Breadth ── ── ── ── ── ── ── ── ── ── ── ── */}
                {cell("up_25_q",     fmtN(r.up_25_q),     clsUp25q(r.up_25_q,    pairPosQ))}
                {cell("down_25_q",   fmtN(r.down_25_q),   clsDn25q(r.down_25_q,  pairPosQ))}
                {cell("up_25_m",     fmtN(r.up_25_m),     clsUp25m(r.up_25_m,    pairPosM))}
                {cell("down_25_m",   fmtN(r.down_25_m),   clsDn25m(r.down_25_m,  pairPosM))}
                {cell("up_50_m",     fmtN(r.up_50_m),     clsUp50m(r.up_50_m))}
                {cell("down_50_m",   fmtN(r.down_50_m),   clsDn50m(r.down_50_m))}
                {cell("up_13_34d",   fmtN(r.up_13_34d),   clsUp13(r.up_13_34d,   pairPos34))}
                {cell("down_13_34d", fmtN(r.down_13_34d), clsDn13(r.down_13_34d, pairPos34))}

                {/* 10x ATR Ext — amber warning when many stocks extended */}
                <td
                  className={`px-1 py-1 text-right whitespace-nowrap font-mono
                    ${clsAtrExt(r.atr_10x_ext, r.atr_10x_ext != null)} hover:brightness-125`}
                  onClick={r.atr_10x_ext != null
                    ? () => onOpenModal("atr_ext", "10x ATR Extended", r.date, isLatest)
                    : undefined}
                  title={r.atr_10x_ext != null ? `View 10x ATR Extended stocks — ${r.date_display}` : undefined}
                >
                  {r.atr_10x_ext != null ? fmtN(r.atr_10x_ext) : "—"}
                </td>

                {/* >50 DMA — red below 30%, green above 80% */}
                <td
                  className={`px-1 py-1 text-right whitespace-nowrap font-mono
                    ${clsAbove50dma(r.above_50dma_pct, r.above_50dma_pct != null)} hover:brightness-125`}
                  onClick={r.above_50dma_pct != null
                    ? () => onOpenModal("above50dma", ">50 DMA", r.date, isLatest)
                    : undefined}
                  title={r.above_50dma_pct != null ? `View stocks above 50 DMA — ${r.date_display}` : undefined}
                >
                  {r.above_50dma_pct != null ? `${r.above_50dma_pct.toFixed(1)}%` : "—"}
                </td>

                {/* Stock Universe $1B+ */}
                <td className="px-1 py-1 text-right text-violet-300/80 whitespace-nowrap font-mono">
                  {r.universe_1b != null ? fmtN(r.universe_1b) : "—"}
                </td>

                {/* Stock Universe (Worden) */}
                <td className="px-1 py-1 text-right text-amber-300/80 whitespace-nowrap">
                  {fmtN(r.worden_universe)}
                </td>

                {/* T2108 — TEAL when ≤20 (oversold buy signal), amber when ≥80 */}
                <td className={`px-1 py-1 text-right whitespace-nowrap ${clsT2108(r.t2108)}`}>
                  {r.t2108 != null ? `${r.t2108.toFixed(1)}%` : "—"}
                </td>

                {/* S&P */}
                <td className="px-1 py-1 text-right text-amber-300/80 whitespace-nowrap">
                  {fmtN(r.sp_index)}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
});

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

const MarketBreadthMonitor = memo(function MarketBreadthMonitor() {
  const [data, setData]             = useState(null);
  const [loading, setLoading]       = useState(true);
  const [error, setError]           = useState(null);
  const [modal, setModal]           = useState(null); // { filter, label, date, isLatest }
  const [clipGroups, setClipGroups] = useState([]);   // [{ id, label, tickers, sentiment }]
  const [clipOpen, setClipOpen]     = useState(false);
  const abortRef                    = useRef(null);

  const openModal  = useCallback((filter, label, date, isLatest) => setModal({ filter, label, date, isLatest }), []);
  const closeModal = useCallback(() => setModal(null), []);

  // Add a group of tickers to the clipboard
  const addToClipboard = useCallback((label, tickers, filter) => {
    if (!tickers.length) return;
    const sentiment = BULLISH_FILTERS.has(filter) ? "bullish" : "bearish";
    setClipGroups((prev) => {
      // If a group with the same label+sentiment already exists, replace it
      const exists = prev.findIndex((g) => g.label === label && g.sentiment === sentiment);
      if (exists >= 0) {
        const next = [...prev];
        next[exists] = { ...next[exists], tickers: [...new Set([...next[exists].tickers, ...tickers])] };
        return next;
      }
      return [...prev, { id: Date.now(), label, tickers, sentiment }];
    });
    setClipOpen(true);
  }, []);

  const removeGroup = useCallback((id) => {
    setClipGroups((prev) => prev.filter((g) => g.id !== id));
  }, []);

  const clearTab = useCallback((tab) => {
    setClipGroups((prev) => prev.filter((g) => g.sentiment !== tab));
  }, []);

  const totalClipCount = clipGroups.reduce((s, g) => s + g.tickers.length, 0);

  const load = async () => {
    setLoading(true);
    setError(null);
    abortRef.current?.abort();
    const ctrl = new AbortController();
    abortRef.current = ctrl;

    try {
      const res = await fetch(
        `${process.env.PUBLIC_URL}/breadth_monitor.json?_=${Date.now()}`,
        { signal: ctrl.signal }
      );
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = await res.json();
      setData(json);
    } catch (e) {
      if (e.name === "AbortError") return;
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void load();
    return () => abortRef.current?.abort();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Loading ──────────────────────────────────────────────────────────────
  if (loading) return <Skeleton />;

  // ── Error ────────────────────────────────────────────────────────────────
  if (error || !data) {
    return (
      <div className="rounded-xl border border-rose-900/40 bg-rose-950/20 px-4 py-4 text-sm text-rose-200">
        <p className="font-semibold">Market Monitor unavailable</p>
        <p className="mt-1 text-xs text-rose-300/80">{error ?? "Unknown error"}</p>
        <button
          onClick={() => void load()}
          className="mt-2 text-xs text-slate-400 underline hover:text-slate-200"
        >
          Retry
        </button>
      </div>
    );
  }

  const rows = data.rows ?? [];
  const latest = rows[0] ?? null;
  const latestDate = latest?.date ?? null;

  return (
    <div className="rounded-xl border border-gray-800 bg-gray-900">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-gray-800 px-4 py-3">
        <div className="flex items-center gap-2">
          <BarChart3 className="h-4 w-4 text-emerald-400" />
          <div>
            <h3 className="text-sm font-semibold text-slate-100">Stockbee Market Monitor</h3>
            <p className="text-xs text-slate-500">
              Sheet {data.sheet_year ?? "—"} ·{" "}
              {data.fetched_at_utc
                ? `Updated ${new Date(data.fetched_at_utc).toLocaleString()}`
                : "—"}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {data.blog_url && (
            <a
              href={data.blog_url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1 text-xs text-slate-500 hover:text-emerald-400"
            >
              stockbee MM <ExternalLink className="h-3 w-3" />
            </a>
          )}
          <button
            onClick={() => void load()}
            title="Refresh"
            className="flex items-center gap-1 rounded px-2 py-1 text-xs text-slate-400 hover:bg-gray-800 hover:text-slate-200"
          >
            <RefreshCw className="h-3 w-3" />
            Refresh
          </button>

          {/* Clipboard badge */}
          <div className="relative">
            <button
              onClick={() => setClipOpen((o) => !o)}
              title="Watchlist Clipboard"
              className={`relative flex items-center gap-1 rounded px-2 py-1 text-xs transition-colors
                ${clipOpen ? "bg-zinc-700 text-zinc-100" : "text-slate-400 hover:bg-gray-800 hover:text-slate-200"}`}
            >
              <Clipboard className="h-4 w-4" />
              {totalClipCount > 0 && (
                <span className="absolute -right-1.5 -top-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-emerald-500 text-[10px] font-bold text-white leading-none">
                  {totalClipCount > 99 ? "99+" : totalClipCount}
                </span>
              )}
            </button>

            {clipOpen && (
              <WatchlistClipboard
                groups={clipGroups}
                onRemoveGroup={removeGroup}
                onClear={clearTab}
                onClose={() => setClipOpen(false)}
              />
            )}
          </div>
        </div>
      </div>

      {/* Gemini AI Breadth Read (Stockbee style) */}
      {rows.length > 0 && (
        <GeminiBreadthRead
          rows={rows}
          precomputedAnalysis={data.gemini_analysis ?? null}
        />
      )}

      {/* Quick-read rule-based badges */}
      {latest && (
        <div className="border-b border-gray-800 px-4 py-2">
          <AnalysisPanel row={latest} />
        </div>
      )}

      {/* Table */}
      <div className="p-4">
        {rows.length === 0 ? (
          <p className="text-center text-sm text-slate-500 py-8">No breadth data available.</p>
        ) : (
          <BreadthTable rows={rows} latestDate={latestDate} onOpenModal={openModal} />
        )}
      </div>

      {/* Footer note */}
      <div className="border-t border-gray-800 px-4 py-2">
        <p className="text-xs text-slate-600">
          Data from Stockbee Market Monitor spreadsheet. Refreshed daily after market close.
          Click any cell to drill into individual stocks for that day.
          Historical data is archived starting from the next trading day after this update.
        </p>
      </div>

      {/* Drill-down modal */}
      {modal && (
        <BreadthStockModal
          filter={modal.filter}
          filterLabel={modal.label}
          date={modal.date}
          isLatest={modal.isLatest}
          onClose={closeModal}
          onAddToClipboard={addToClipboard}
        />
      )}
    </div>
  );
});

export default MarketBreadthMonitor;
