/**
 * MarketBreadthMonitor.js
 *
 * Stockbee Market Monitor table for Power Theme.
 * Reads from /breadth_monitor.json (generated by breadth_monitor.py).
 *
 * Columns: DATE | UP 4%+ | DN 4%+ | 5D R | 10D R |
 *          UP 25% Q | DN 25% Q | UP 25% M | DN 25% M |
 *          UP 50% M | DN 50% M | UP 13% 34D | DN 13% 34D |
 *          10x ATR Ext | >50 DMA | Share Universe | T2108 | S&P
 */

import { memo, useEffect, useRef, useState } from "react";
import { BarChart3, ExternalLink, RefreshCw } from "lucide-react";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function fmtN(n) {
  if (n == null || !Number.isFinite(n)) return "—";
  return Number.isInteger(n) ? String(n) : n.toFixed(2);
}

function t2108Badge(v) {
  if (v == null || !Number.isFinite(v)) return null;
  if (v < 20) return { label: "Oversold (<20)", cls: "bg-rose-900/60 text-rose-300" };
  if (v > 70) return { label: "Overbought (>70)", cls: "bg-amber-900/60 text-amber-300" };
  return { label: "Neutral (20–70)", cls: "bg-slate-700/60 text-slate-300" };
}

// ---------------------------------------------------------------------------
// Loading skeleton
// ---------------------------------------------------------------------------

const Skeleton = memo(function Skeleton() {
  return (
    <div className="rounded-xl border border-gray-800 bg-gray-900 p-4">
      <div className="mb-3 h-5 w-48 animate-pulse rounded bg-gray-700" />
      <div className="space-y-2">
        {[...Array(6)].map((_, i) => (
          <div key={i} className="h-6 animate-pulse rounded bg-gray-800" />
        ))}
      </div>
    </div>
  );
});

// ---------------------------------------------------------------------------
// Analysis badge
// ---------------------------------------------------------------------------

const Badge = memo(function Badge({ label, variant }) {
  const cls = {
    "Extreme Bullish": "bg-emerald-900/70 text-emerald-300 border-emerald-700",
    Bullish:           "bg-emerald-900/40 text-emerald-400 border-emerald-800",
    Caution:           "bg-amber-900/40  text-amber-400  border-amber-800",
    Bearish:           "bg-rose-900/40   text-rose-400   border-rose-800",
    Neutral:           "bg-slate-800     text-slate-400  border-slate-700",
    Oversold:          "bg-rose-900/60   text-rose-300   border-rose-700",
    Overbought:        "bg-amber-900/60  text-amber-300  border-amber-700",
  }[variant] ?? "bg-slate-800 text-slate-400 border-slate-700";

  return (
    <span className={`inline-flex items-center rounded-full border px-2 py-0.5 text-xs font-medium ${cls}`}>
      {label}
    </span>
  );
});

// ---------------------------------------------------------------------------
// Analysis panel (derived from the latest row)
// ---------------------------------------------------------------------------

const AnalysisPanel = memo(function AnalysisPanel({ row }) {
  if (!row) return null;

  const up4 = row.up_4_pct ?? 0;
  const dn4 = row.down_4_pct ?? 0;
  const thrust = dn4 <= 0 ? up4 > 0 : up4 > 3 * dn4;

  const shortTerm = thrust
    ? { label: "Extremely Bullish / Thrust", badge: "Extreme Bullish" }
    : up4 > dn4
    ? { label: "Bulls leading on the 4%+ tape", badge: "Bullish" }
    : { label: "Bears competitive on the 4%+ tape", badge: "Caution" };

  const upQ = row.up_25_q, dnQ = row.down_25_q;
  const quarterly =
    upQ != null && dnQ != null && dnQ > upQ
      ? { label: "Quarterly breadth skewed negative (dn > up)", badge: "Bearish" }
      : { label: "Quarterly breadth not dominated by losers", badge: "Neutral" };

  const t = t2108Badge(row.t2108);

  return (
    <div className="flex flex-wrap gap-3">
      <div className="flex items-center gap-2 text-xs text-slate-400">
        <span>Short-term:</span>
        <Badge label={shortTerm.badge} variant={shortTerm.badge} />
        <span className="text-slate-500">{shortTerm.label}</span>
      </div>
      <div className="flex items-center gap-2 text-xs text-slate-400">
        <span>Quarterly:</span>
        <Badge label={quarterly.badge} variant={quarterly.badge} />
        <span className="text-slate-500">{quarterly.label}</span>
      </div>
      {t && (
        <div className="flex items-center gap-2 text-xs text-slate-400">
          <span>T2108:</span>
          <Badge label={t.label} variant={t.label.startsWith("Over") ? (t.label.includes("sold") ? "Oversold" : "Overbought") : "Neutral"} />
        </div>
      )}
    </div>
  );
});

// ---------------------------------------------------------------------------
// Main table
// ---------------------------------------------------------------------------

const BreadthTable = memo(function BreadthTable({ rows }) {
  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[1040px] border-collapse text-left">
        <caption className="sr-only">Stockbee Market Monitor breadth history.</caption>
        <thead>
          <tr className="border-b border-gray-800">
            <th className="sticky left-0 z-10 bg-gray-900 py-2 pr-3 text-xs font-medium text-emerald-400 whitespace-nowrap">DATE</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">UP 4%+</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">DN 4%+</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">5D R</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">10D R</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">UP 25% Q</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">DN 25% Q</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">UP 25% M</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">DN 25% M</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">UP 50% M</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">DN 50% M</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">UP 13% 34D</th>
            <th className="px-1 py-2 text-xs font-medium text-emerald-400 whitespace-nowrap">DN 13% 34D</th>
            <th className="px-1 py-2 text-xs font-medium text-purple-400 whitespace-nowrap">10x ATR Ext</th>
            <th className="px-1 py-2 text-xs font-medium text-sky-400 whitespace-nowrap">&gt;50 DMA</th>
            <th className="px-1 py-2 text-xs font-medium text-amber-400 whitespace-nowrap">Share Universe</th>
            <th className="px-1 py-2 text-xs font-medium text-amber-400 whitespace-nowrap">T2108</th>
            <th className="px-1 py-2 text-xs font-medium text-amber-400 whitespace-nowrap">S&amp;P</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => {
            const isLatest = i === 0;
            const bearish = r.up_25_q != null && r.down_25_q != null && r.up_25_q < r.down_25_q;
            const up4hi = r.up_4_pct != null && r.up_4_pct > 600;
            const t2108Low = r.t2108 != null && r.t2108 < 20;

            return (
              <tr
                key={r.date}
                className={`border-b border-gray-800/80 font-mono text-xs ${
                  isLatest ? "bg-gray-800/30" : ""
                } ${bearish ? "text-rose-200/70" : "text-slate-300"}`}
              >
                {/* DATE — sticky */}
                <td className="sticky left-0 z-10 bg-gray-900 py-1 pr-3 font-mono text-xs whitespace-nowrap">
                  {isLatest ? (
                    <span className="font-semibold text-emerald-400">{r.date_display}</span>
                  ) : (
                    r.date_display
                  )}
                </td>

                {/* UP 4%+ */}
                <td className={`px-1 py-1 text-right whitespace-nowrap ${up4hi ? "font-semibold text-emerald-300" : ""}`}>
                  {fmtN(r.up_4_pct)}
                </td>

                {/* DN 4%+ */}
                <td className="px-1 py-1 text-right whitespace-nowrap">{fmtN(r.down_4_pct)}</td>

                {/* 5D R */}
                <td className="px-1 py-1 text-right whitespace-nowrap">{fmtN(r.ratio_5d)}</td>

                {/* 10D R */}
                <td className="px-1 py-1 text-right whitespace-nowrap">{fmtN(r.ratio_10d)}</td>

                {/* UP 25% Q */}
                <td className="px-1 py-1 text-right whitespace-nowrap">{fmtN(r.up_25_q)}</td>

                {/* DN 25% Q */}
                <td className={`px-1 py-1 text-right whitespace-nowrap ${bearish ? "text-rose-400" : ""}`}>
                  {fmtN(r.down_25_q)}
                </td>

                {/* UP 25% M */}
                <td className="px-1 py-1 text-right whitespace-nowrap">{fmtN(r.up_25_m)}</td>

                {/* DN 25% M */}
                <td className="px-1 py-1 text-right whitespace-nowrap">{fmtN(r.down_25_m)}</td>

                {/* UP 50% M */}
                <td className="px-1 py-1 text-right whitespace-nowrap">{fmtN(r.up_50_m)}</td>

                {/* DN 50% M */}
                <td className="px-1 py-1 text-right whitespace-nowrap">{fmtN(r.down_50_m)}</td>

                {/* UP 13% 34D */}
                <td className="px-1 py-1 text-right whitespace-nowrap">{fmtN(r.up_13_34d)}</td>

                {/* DN 13% 34D */}
                <td className="px-1 py-1 text-right whitespace-nowrap">{fmtN(r.down_13_34d)}</td>

                {/* 10x ATR Ext */}
                <td className="px-1 py-1 text-right text-purple-300 whitespace-nowrap">
                  {r.atr_10x_ext != null ? fmtN(r.atr_10x_ext) : "—"}
                </td>

                {/* >50 DMA */}
                <td className="px-1 py-1 text-right text-sky-300 whitespace-nowrap">
                  {r.above_50dma_pct != null ? `${r.above_50dma_pct.toFixed(1)}%` : "—"}
                </td>

                {/* Share Universe */}
                <td className="px-1 py-1 text-right text-amber-300/80 whitespace-nowrap">
                  {fmtN(r.worden_universe)}
                </td>

                {/* T2108 */}
                <td className={`px-1 py-1 text-right whitespace-nowrap ${t2108Low ? "font-semibold text-rose-400" : "text-amber-300/80"}`}>
                  {r.t2108 != null ? `${r.t2108.toFixed(1)}%` : "—"}
                </td>

                {/* S&P */}
                <td className="px-1 py-1 text-right text-amber-300/80 whitespace-nowrap">
                  {fmtN(r.sp_index)}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
});

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

const MarketBreadthMonitor = memo(function MarketBreadthMonitor() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [lastRefresh, setLastRefresh] = useState(null);
  const abortRef = useRef(null);

  const load = async () => {
    setLoading(true);
    setError(null);
    abortRef.current?.abort();
    const ctrl = new AbortController();
    abortRef.current = ctrl;

    try {
      const res = await fetch(
        `${process.env.PUBLIC_URL}/breadth_monitor.json?_=${Date.now()}`,
        { signal: ctrl.signal }
      );
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const json = await res.json();
      setData(json);
      setLastRefresh(new Date());
    } catch (e) {
      if (e.name === "AbortError") return;
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    void load();
    return () => abortRef.current?.abort();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Loading ──────────────────────────────────────────────────────────────
  if (loading) return <Skeleton />;

  // ── Error ────────────────────────────────────────────────────────────────
  if (error || !data) {
    return (
      <div className="rounded-xl border border-rose-900/40 bg-rose-950/20 px-4 py-4 text-sm text-rose-200">
        <p className="font-semibold">Market Monitor unavailable</p>
        <p className="mt-1 text-xs text-rose-300/80">{error ?? "Unknown error"}</p>
        <button
          onClick={() => void load()}
          className="mt-2 text-xs text-slate-400 underline hover:text-slate-200"
        >
          Retry
        </button>
      </div>
    );
  }

  const rows = data.rows ?? [];
  const latest = rows[0] ?? null;

  return (
    <div className="rounded-xl border border-gray-800 bg-gray-900">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-gray-800 px-4 py-3">
        <div className="flex items-center gap-2">
          <BarChart3 className="h-4 w-4 text-emerald-400" />
          <div>
            <h3 className="text-sm font-semibold text-slate-100">Stockbee Market Monitor</h3>
            <p className="text-xs text-slate-500">
              Sheet {data.sheet_year ?? "—"} ·{" "}
              {data.fetched_at_utc
                ? `Updated ${new Date(data.fetched_at_utc).toLocaleString()}`
                : "—"}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {data.blog_url && (
            <a
              href={data.blog_url}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1 text-xs text-slate-500 hover:text-emerald-400"
            >
              stockbee MM <ExternalLink className="h-3 w-3" />
            </a>
          )}
          <button
            onClick={() => void load()}
            title="Refresh"
            className="flex items-center gap-1 rounded px-2 py-1 text-xs text-slate-400 hover:bg-gray-800 hover:text-slate-200"
          >
            <RefreshCw className="h-3 w-3" />
            Refresh
          </button>
        </div>
      </div>

      {/* Analysis */}
      {latest && (
        <div className="border-b border-gray-800 px-4 py-2">
          <AnalysisPanel row={latest} />
        </div>
      )}

      {/* Table */}
      <div className="p-4">
        {rows.length === 0 ? (
          <p className="text-center text-sm text-slate-500 py-8">No breadth data available.</p>
        ) : (
          <BreadthTable rows={rows} />
        )}
      </div>

      {/* Footer note */}
      <div className="border-t border-gray-800 px-4 py-2">
        <p className="text-xs text-slate-600">
          Data from Stockbee Market Monitor spreadsheet. Refreshed daily after market close.
          10x ATR Ext and &gt;50 DMA columns appear when available.
        </p>
      </div>
    </div>
  );
});

export default MarketBreadthMonitor;
